---
permalink: sg6000/maintaining-sg6000-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Möglicherweise müssen Sie auf der SG6000-Appliance Wartungsarbeiten durchführen. Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde. 
---
= Warten Sie die SG6000-Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie auf der SG6000-Appliance Wartungsarbeiten durchführen. Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde.

Um Serviceunterbrechungen zu vermeiden, vergewissern Sie sich, dass alle anderen Speicherknoten mit dem Raster verbunden sind, bevor Sie das Gerät herunterfahren oder das Gerät während eines geplanten Wartungsfensters herunterfahren, wenn die Serviceunterbrechungen akzeptabel sind. Weitere Informationen finden Sie unter xref:../monitor/monitoring-node-connection-states.adoc[Monitoring der Verbindungsstatus der Nodes].


IMPORTANT: Wenn Sie jemals eine ILM-Regel verwendet haben, die nur eine Kopie eines Objekts erstellt, müssen Sie die Appliance während eines geplanten Wartungsfensters herunterfahren. Andernfalls verlieren Sie während des Wartungsvorgangs, die einen Storage-Node außer Betrieb nimmt, möglicherweise vorübergehend den Zugriff auf diese Objekte. Weitere Informationen finden Sie unter xref:../ilm/index.adoc[Verwalten von Objekten mit Information Lifecycle Management].
