---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: Sie können zu einem anderen RAID-Modus auf der Appliance wechseln, um Ihre Anforderungen an Storage und Recovery zu erfüllen. Sie können den Modus nur ändern, bevor Sie den Appliance-Speicherknoten bereitstellen. 
---
= Optional: Ändern des RAID-Modus (nur SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können zu einem anderen RAID-Modus auf der Appliance wechseln, um Ihre Anforderungen an Storage und Recovery zu erfüllen. Sie können den Modus nur ändern, bevor Sie den Appliance-Speicherknoten bereitstellen.

.Was Sie benötigen
* Sie verwenden jeden Client, der eine Verbindung zu StorageGRID herstellen kann.
* Der Client verfügt über eine xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].


.Über diese Aufgabe
Vor der Bereitstellung der Appliance als Storage Node können Sie eine der folgenden Volume-Konfigurationsoptionen wählen:

* *DDP*: Dieser Modus verwendet zwei Paritätslaufwerke pro acht Datenlaufwerke. Dies ist der Standard- und empfohlene Modus für alle Appliances. Im Vergleich zu RAID 6 bietet DDP eine bessere System-Performance, geringere Wiederherstellungszeiten nach Laufwerksausfällen und einfaches Management.
+

IMPORTANT: Aufgrund der beiden SSDs bietet DDP in SG6060 Appliances keinen Schubladenschutz. Der Schutz vor Schubladenverlusten ist in allen Erweiterungs-Shelfs, die zu einem SG6060 hinzugefügt werden, wirksam.

* *DDP16*: In diesem Modus werden für alle 16 Datenlaufwerke zwei Paritätslaufwerke verwendet. Dies führt im Vergleich zu DDP zu einer höheren Storage-Effizienz. Im Vergleich zu RAID 6 bietet DDP16 eine bessere System-Performance, geringere Wiederherstellungszeiten nach Laufwerksausfällen, einfaches Management und vergleichbare Storage-Effizienz. Um den DDP16-Modus zu verwenden, muss Ihre Konfiguration mindestens 20 Laufwerke enthalten. DDP16 bietet keinen Schubladenschutz.
* *RAID 6*: Dieser Modus verwendet zwei Paritätslaufwerke pro 16 oder mehr Datenlaufwerken. Für die Verwendung des RAID 6-Modus muss Ihre Konfiguration mindestens 20 Laufwerke enthalten. Obwohl RAID-6 die Storage-Effizienz der Appliance im Vergleich zu DDP erhöhen kann, wird dies in den meisten StorageGRID-Umgebungen nicht empfohlen.



IMPORTANT: Wenn bereits Volumes konfiguriert wurden oder bereits StorageGRID installiert war, werden die Volumes durch eine Änderung des RAID-Modus entfernt und ersetzt. Alle Daten auf diesen Volumes gehen verloren.

.Schritte
. Öffnen Sie einen Browser, und geben Sie eine der IP-Adressen für den Computing-Controller der Appliance ein.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` Die IP-Adresse des Compute-Controllers (nicht des Storage-Controllers) in einem der drei StorageGRID-Netzwerke.

+
Die Startseite des StorageGRID-Appliance-Installationsprogramms wird angezeigt.

. Wählen Sie *Erweitert* *RAID-Modus*.
. Wählen Sie auf der Seite *RAID-Modus konfigurieren* den gewünschten RAID-Modus aus der Dropdown-Liste Modus aus.
. Klicken Sie Auf *Speichern*.


.Verwandte Informationen
http://["NetApp E-Series Systems Documentation Site"^]
