---
permalink: sg6000/preparing-site-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility 
summary: Vor der Installation der Appliance müssen Sie sicherstellen, dass der Standort und das Rack, das Sie verwenden möchten, die Spezifikationen einer StorageGRID Appliance erfüllen. 
---
= Site vorbereiten (SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation der Appliance müssen Sie sicherstellen, dass der Standort und das Rack, das Sie verwenden möchten, die Spezifikationen einer StorageGRID Appliance erfüllen.

.Schritte
. Vergewissern Sie sich, dass der Standort die Anforderungen an Temperatur, Luftfeuchtigkeit, Höhenbereich, Luftstrom, Wärmeableitung, Verkabelung, Strom und Erdung. Weitere Informationen finden Sie im NetApp Hardware Universe.
. Stellen Sie sicher, dass Ihr Standort 240-Volt-Wechselstrom für die SG6060- oder 120-Volt-Wechselstromversorgung des SGF6024 bereitstellt.
. Passen Sie zu 48.3 Shelfs dieser Größe (ohne Kabel) ein 19-cm-Gehäuse oder -Rack an:
+
|===
| Typ des Shelfs | Höhe | Breite | Tiefe | Maximales Gewicht 


 a| 
*E2860 Controller-Shelf* für SG6060
 a| 
6.87 Zoll

(17.46 cm)
 a| 
17.66 Zoll

(44.86 cm)
 a| 
38.25 Zoll

(97.16 cm)
 a| 
250 lb.

(113 kg)



 a| 
*Optionales Erweiterungs-Shelf* für SG6060 (ein oder zwei)
 a| 
6.87 Zoll

(17.46 cm)
 a| 
17.66 Zoll

(44.86 cm)
 a| 
38.25 Zoll

(97.16 cm)
 a| 
250 lb.

(113 kg)



 a| 
*EF570 Controller Shelf* für SGF6024
 a| 
3.35 Zoll

(8.50 cm)
 a| 
17.66 Zoll

(44.86 cm)
 a| 
19.00 Zoll

(48.26 cm)
 a| 
51.74 lb.

(23.47 kg)



 a| 
*SG6000-CN-Controller* für jedes Gerät
 a| 
1.70 Zoll

(4.32 cm)
 a| 
17.32 Zoll

(44.0 cm)
 a| 
32.0 Zoll

(81.3 cm)
 a| 
39 lb.

(17.7 kg)

|===
. Entscheiden Sie, wo Sie das Gerät installieren möchten.
+

CAUTION: Installieren Sie bei der Installation des E2860 Controller-Shelfs oder optionaler Erweiterungs-Shelfs die Hardware von unten nach oben im Rack oder Schrank, um zu vermeiden, dass das System umkippt. Installieren Sie den SG6000-CN Controller über dem E2860 Controller-Shelf und Erweiterungs-Shelfs, um sicherzustellen, dass sich die schwersten Geräte unten im Rack oder Rack befinden.

+

IMPORTANT: Stellen Sie vor der Installation sicher, dass die im Lieferumfang des Geräts enthaltenen 0,5-m-Glasfaserkabel oder -Kabel lang genug für das geplante Layout sind.



.Verwandte Informationen
https://["NetApp Hardware Universe"^]

https://["NetApp Interoperabilitäts-Matrix-Tool"^]
