---
permalink: sg6000/replacing-hardware-components-in-optional-60-drive-expansion-shelf.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, i/o module, input/output module, power supply, fan, 60-drive expansion shelf, expansion shelf 
summary: Möglicherweise müssen Sie ein ein ein-/Ausgabemodul, ein Netzteil oder einen Lüfter im Erweiterungs-Shelf ersetzen. 
---
= Ersetzen Sie Hardwarekomponenten in dem optionalen Erweiterungs-Shelf für 60 Laufwerke
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie ein ein ein-/Ausgabemodul, ein Netzteil oder einen Lüfter im Erweiterungs-Shelf ersetzen.

.Was Sie und#8217;ll benötigen
* Sie haben das Verfahren zum Austausch der E-Series Hardware.
* Sie haben die Storage Appliance physisch gefunden, wo Sie im Datacenter Erweiterungs-Shelf-Hardware-Komponenten ersetzen.
+
xref:locating-controller-in-data-center.adoc[Controller im Datacenter finden]



Um ein Input/Output-Modul (IOM) in einem Erweiterungs-Shelf mit 60 Laufwerken zu ersetzen, lesen Sie die Anweisungen in diesen Anleitungen zum Austauschen eines Storage-Controllers.

Um ein Netzteil oder einen Lüfter in einem Erweiterungs-Shelf mit 60 Laufwerken zu ersetzen, rufen Sie die E-Series Verfahren zur Wartung von Hardware mit 60 Laufwerken auf.

|===
| FRU | Weitere Informationen finden Sie in den Anweisungen zur E-Series 


 a| 
Eingangs-/Ausgangsmodul (IOM)
 a| 
Ersetzen eines EAM



 a| 
Leistungsbehälter
 a| 
Ersetzen Sie den Netzbehälter (60 Laufwerke).



 a| 
Gebläsebehälter
 a| 
Lüfterbehälter austauschen (60 Laufwerke)

|===