---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: Möglicherweise müssen Sie den SG6000-CN-Controller austauschen, wenn er nicht optimal funktioniert oder ausgefallen ist. 
---
= Tauschen Sie den SG6000-CN Controller aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie den SG6000-CN-Controller austauschen, wenn er nicht optimal funktioniert oder ausgefallen ist.

.Was Sie und#8217;ll benötigen
* Sie verfügen über einen Ersatzcontroller mit derselben Teilenummer wie der zu ersetzenden Controller.
* Sie verfügen über Etiketten, um jedes Kabel, das mit dem Controller verbunden ist, zu identifizieren.
* Der Controller ist physisch zu finden, der im Datacenter ersetzt werden soll.
+
xref:locating-controller-in-data-center.adoc[Controller im Datacenter finden]



Der Gerätespeicherknoten kann nicht aufgerufen werden, wenn Sie den SG6000-CN-Controller austauschen. Wenn der SG6000-CN-Controller ausreichend funktioniert, können Sie zu Beginn dieses Verfahrens ein kontrolliertes Herunterfahren durchführen.


NOTE: Wenn Sie den Controller vor dem Installieren der StorageGRID-Software ersetzen, können Sie nach Abschluss dieses Verfahrens möglicherweise nicht sofort auf den StorageGRID Appliance Installer zugreifen. Während Sie von anderen Hosts im selben Subnetz wie die Appliance auf das Installationsprogramm für StorageGRID-Geräte zugreifen können, können Sie nicht von Hosts in anderen Subnetzen darauf zugreifen. Diese Bedingung sollte sich innerhalb von 15 Minuten lösen (wenn Einträge im ARP-Cache für die ursprüngliche Controller-Zeit erforderlich sind), oder Sie können den Zustand sofort löschen, indem Sie alle alten ARP-Cacheeinträge manuell vom lokalen Router oder Gateway löschen.

.Schritte
. Wenn der SG6000-CN-Controller ausreichend funktioniert, um ein kontrolliertes Herunterfahren zu ermöglichen, fahren Sie den SG6000-CN-Controller herunter.
+
xref:shutting-down-sg6000-cn-controller.adoc[Fahren Sie den SG6000-CN-Controller herunter]

. Überprüfen Sie anhand einer von zwei Methoden, ob die Stromversorgung für den SG6000-CN-Controller ausgeschaltet ist:
+
** Die Betriebsanzeige-LED an der Vorderseite des Controllers leuchtet nicht.
** Die Seite Power Control der BMC-Schnittstelle zeigt an, dass der Controller aus ist.


. Wenn die mit dem Controller verbundenen StorageGRID-Netzwerke DHCP-Server verwenden, aktualisieren Sie die Einstellungen für DNS/Netzwerk und IP-Adresse.
+
.. Suchen Sie das MAC-Adressenetikett auf der Vorderseite des SG6000-CN-Controllers und legen Sie die MAC-Adresse für den Admin-Netzwerkanschluss fest.
+

NOTE: Auf dem MAC-Adressenetikett wird die MAC-Adresse für den BMC-Verwaltungsport aufgelistet. + um die MAC-Adresse für den Admin-Netzwerkanschluss zu ermitteln, müssen Sie der Hexadezimalzahl auf dem Etikett *2* hinzufügen. Wenn die MAC-Adresse auf dem Etikett beispielsweise mit *09* endet, endet die MAC-Adresse für den Admin-Port in *0B*. Wenn die MAC-Adresse auf dem Etikett mit *(_y_)FF* endet, endet die MAC-Adresse für den Admin-Port in *(_y_+1)01*. Sie können diese Berechnung einfach durchführen, indem Sie den Rechner unter Windows öffnen, ihn auf den Programmiermodus setzen, Hex auswählen, die MAC-Adresse eingeben und dann *+ 2 =* eingeben.

.. Bitten Sie den Netzwerkadministrator, die DNS/Netzwerk- und IP-Adresse des entfernten Controllers mit der MAC-Adresse des Ersatzcontrollers zu verknüpfen.
+

IMPORTANT: Sie müssen sicherstellen, dass alle IP-Adressen für den ursprünglichen Controller aktualisiert wurden, bevor Sie den Ersatz-Controller mit Strom versorgen. Andernfalls erhält der Controller neue DHCP-IP-Adressen, wenn er gebootet wird und kann möglicherweise nicht die Verbindung mit StorageGRID wiederherstellen. Dieser Schritt gilt für alle StorageGRID-Netzwerke, die mit dem Controller verbunden sind.

+

NOTE: Wenn der ursprüngliche Controller statische IP-Adresse verwendet hat, übernimmt der neue Controller automatisch die IP-Adressen des entfernten Controllers.



. Entfernen und ersetzen Sie den SG6000-CN-Controller:
+
.. Beschriften Sie die Kabel und trennen Sie dann die Kabel und alle SFP+ oder SFP28 Transceiver.
+

IMPORTANT: Um eine verminderte Leistung zu vermeiden, dürfen die Kabel nicht verdreht, gefaltet, gequetscht oder treten.

.. Entfernen Sie den fehlerhaften Controller aus dem Schrank oder Rack.
.. Setzen Sie den Ersatzcontroller in den Schrank oder Rack ein.
.. Ersetzen Sie die Kabel und alle SFP+ oder SFP28 Transceiver.
.. Schalten Sie den Controller ein, und überwachen Sie die Controller-LEDs und die Boot-Codes.


. Vergewissern Sie sich, dass der Appliance Storage Node im Grid Manager angezeigt wird und keine Alarme angezeigt werden.
. Wählen Sie im Grid Manager *NODES* aus, und überprüfen Sie, ob die BMC-IP-Adresse für den Knoten-Controller korrekt ist.
+
Wenn die Node-Controller-IP-Adresse ungültig ist oder sich nicht im erwarteten Bereich befindet, konfigurieren Sie die IP-Adresse gemäß den Recovery- und Wartungsanweisungen neu.

+

NOTE: Wenn Sie während der ursprünglichen Installation zusätzliche Anpassungen vorgenommen haben, z. B. das Festlegen von SNMP-Trap-Zielen oder E-Mail-Benachrichtigungen, sollten Sie die Konfiguration aufzeichnen und validieren und gegebenenfalls erneut anwenden.

+
xref:../maintain/index.adoc[Recovery und Wartung]



xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN: Einbau in Schrank oder Rack]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[Statusanzeigen und Schaltflächen des SG6000-CN Controllers anzeigen]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[Anzeigen von Boot-Codes für SG6000-CN-Controller]
