---
permalink: sg6000/reviewing-appliance-network-connections-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, network connections, network connection, network, connection, grid, admin, client, bmc, management, SANtricity System Manager, SANtricity 
summary: Vor der Installation der StorageGRID Appliance sollten Sie wissen, welche Netzwerke mit der Appliance verbunden werden können. 
---
= Appliance-Netzwerkverbindungen prüfen (SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation der StorageGRID Appliance sollten Sie wissen, welche Netzwerke mit der Appliance verbunden werden können.

Wenn Sie eine StorageGRID-Appliance als Speicherknoten in einem StorageGRID-System bereitstellen, können Sie sie mit folgenden Netzwerken verbinden:

* *Grid-Netzwerk für StorageGRID*: Das Grid-Netzwerk wird für den gesamten internen StorageGRID-Datenverkehr verwendet. Das System bietet Konnektivität zwischen allen Nodes im Grid und allen Standorten und Subnetzen. Das Grid-Netzwerk ist erforderlich.
* *Admin-Netzwerk für StorageGRID*: Das Admin-Netzwerk ist ein geschlossenes Netzwerk, das zur Systemadministration und Wartung verwendet wird. Das Admin-Netzwerk ist in der Regel ein privates Netzwerk und muss nicht zwischen Standorten routingfähig sein. Das Admin-Netzwerk ist optional.
* *Client-Netzwerk für StorageGRID:* das Client-Netzwerk ist ein offenes Netzwerk, das für den Zugriff auf Client-Anwendungen, einschließlich S3 und Swift, verwendet wird. Das Client-Netzwerk ermöglicht den Zugriff auf das Grid-Protokoll, sodass das Grid-Netzwerk isoliert und gesichert werden kann. Das Client-Netzwerk ist optional.
* *Managementnetzwerk für SANtricity System Manager* (optional): Dieses Netzwerk bietet Zugriff auf den SANtricity System Manager auf dem Storage Controller, so dass Sie die Hardwarekomponenten im Storage Controller Shelf überwachen und verwalten können. Dieses Managementnetzwerk kann das gleiche sein wie das Admin-Netzwerk für StorageGRID, oder es kann ein unabhängiges Managementnetzwerk sein.
+
Wenn das optionale SANtricity System Manager-Netzwerk nicht verbunden ist, können Sie einige SANtricity-Funktionen möglicherweise nicht verwenden.

* *BMC-Managementnetzwerk für den SG6000-CN-Controller* (optional): Dieses Netzwerk bietet Zugriff auf den Baseboard-Management-Controller im SG6000-CN, sodass Sie die Hardwarekomponenten des SG6000-CN-Controllers überwachen und verwalten können. Dieses Managementnetzwerk kann das gleiche sein wie das Admin-Netzwerk für StorageGRID, oder es kann ein unabhängiges Managementnetzwerk sein.
+
Wenn das optionale BMC-Managementnetzwerk nicht verbunden ist, sind einige Support- und Wartungsverfahren schwieriger zu bewältigen. Sie können das BMC-Managementnetzwerk außer zu Supportzwecken unverbunden lassen.




NOTE: Ausführliche Informationen zu StorageGRID-Netzwerken finden Sie unter _Rasterprimer_.

.Verwandte Informationen
xref:gathering-installation-information-sg6000.adoc[Erfassen von Installationsinformationen (SG6000)]

xref:cabling-appliance-sg6000.adoc[Kabelgerät (SG6000)]

xref:port-bond-modes-for-sg6000-cn-controller.adoc[Port Bond-Modi für SG6000-CN Controller]

xref:../network/index.adoc[Netzwerkrichtlinien]
