---
permalink: sg6000/unable-to-connect-to-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Wenn Sie keine Verbindung zur Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen. 
---
= Verbindung zum Gerät nicht möglich
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie keine Verbindung zur Appliance herstellen können, liegt möglicherweise ein Netzwerkproblem vor, oder die Hardwareinstallation wurde möglicherweise nicht erfolgreich abgeschlossen.

.Schritte
. Wenn Sie keine Verbindung zum SANtricity-System-Manager herstellen können:
+
.. Versuchen Sie, die Appliance mit der IP-Adresse für entweder Storage Controller im Managementnetzwerk für SANtricity System Manager zu pingen: +
`*ping _Storage_Controller_IP_*`
.. Wenn Sie keine Antwort vom Ping erhalten, bestätigen Sie, dass Sie die richtige IP-Adresse verwenden.
+
Verwenden Sie die IP-Adresse für Management-Port 1 auf einem Storage Controller.

.. Wenn die IP-Adresse korrekt ist, überprüfen Sie die Geräteverkabelung und das Netzwerk-Setup.
+
Falls das Problem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support.

.. Wenn der Ping erfolgreich war, öffnen Sie einen Webbrowser.
.. Geben Sie die URL für SANtricity System Manager ein: +
`*https://_Storage_Controller_IP_*`
+
Die Login-Seite für SANtricity System Manager wird angezeigt.



. Wenn Sie keine Verbindung zum SG6000-CN Controller herstellen können:
+
.. Versuchen Sie, das Gerät mit der IP-Adresse für den SG6000-CN-Controller zu pingen: +
`*ping _SG6000-CN_Controller_IP_*`
.. Wenn Sie keine Antwort vom Ping erhalten, bestätigen Sie, dass Sie die richtige IP-Adresse verwenden.
+
Sie können die IP-Adresse der Appliance im Grid-Netzwerk, im Admin-Netzwerk oder im Client-Netzwerk verwenden.

.. Wenn die IP-Adresse korrekt ist, überprüfen Sie die Geräteverkabelung, SFP-Transceiver und das Netzwerk-Setup.
.. Wenn physischer Zugriff auf das SG6000-CN verfügbar ist, können Sie eine direkte Verbindung zur permanenten Link-lokalen IP verwenden `169.254.0.1` Um die Controller-Netzwerkkonfiguration zu überprüfen und bei Bedarf zu aktualisieren. Detaillierte Anweisungen finden Sie in Schritt 2 unter xref:..//sg6000/accessing-storagegrid-appliance-installer-sg6000.adoc[Zugriff auf das Installationsprogramm der StorageGRID Appliance].
+
Falls das Problem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support.

.. Wenn der Ping erfolgreich war, öffnen Sie einen Webbrowser.
.. Geben Sie die URL für das StorageGRID-Appliance-Installationsprogramm ein: +
`*https://_SG6000-CN_Controller_IP_:8443*`
+
Die Startseite wird angezeigt.




