---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: 'Die Revisionsfreigabe enthält die aktive audit.log-Datei und alle komprimierten Audit-Log-Dateien. Um einfachen Zugriff auf Audit-Protokolle zu erhalten, können Sie den Client-Zugriff auf Audit-Shares sowohl für NFS als auch für CIFS \ konfigurieren (CIFS ist veraltet\). Sie können auch direkt über die Befehlszeile des Admin-Knotens auf Audit-Protokolldateien zugreifen.' 
---
= Zugriff auf die Audit-Log-Datei
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Revisionsfreigabe enthält die aktive `audit.log` Datei und alle komprimierten Audit-Log-Dateien. Um einfachen Zugriff auf Audit-Protokolle zu ermöglichen, können Sie den Client-Zugriff auf Audit-Shares sowohl für NFS als auch für CIFS (CIFS ist veraltet) konfigurieren. Sie können auch direkt über die Befehlszeile des Admin-Knotens auf Audit-Protokolldateien zugreifen.

.Was Sie benötigen
* Sie müssen über spezifische Zugriffsberechtigungen verfügen.
* Sie müssen die haben `Passwords.txt` Datei:
* Sie müssen die IP-Adresse eines Admin-Knotens kennen.


.Schritte
. Melden Sie sich bei einem Admin-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


. Gehen Sie zu dem Verzeichnis, das die Audit-Log-Dateien enthält:
+
`cd /var/local/audit/export`

. Sehen Sie sich die aktuelle oder gespeicherte Audit-Protokolldatei nach Bedarf an.


.Verwandte Informationen
xref:../admin/index.adoc[StorageGRID verwalten]
