---
permalink: audit/audit-messages-and-object-lifecycle.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, object lifecycle, ingest, retrieve, delete, s3, swift, timing, ILM, Information lifecycle management, archive node, archive nodes 
summary: 'Audit-Nachrichten werden bei jeder Aufnahme, jedem Abruf oder jedem Löschen eines Objekts generiert. Sie können diese Transaktionen im Audit-Protokoll identifizieren, indem Sie API-spezifische \(S3 oder Swift\)-Audit-Nachrichten suchen.' 
---
= Überwachungsmeldungen und der Lebenszyklus von Objekten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Audit-Nachrichten werden bei jeder Aufnahme, jedem Abruf oder jedem Löschen eines Objekts generiert. Sie können diese Transaktionen im Audit-Protokoll identifizieren, indem Sie API-spezifische (S3 oder Swift) Audit-Nachrichten suchen.

Überwachungsmeldungen werden durch Kennungen verknüpft, die für jedes Protokoll spezifisch sind.

|===
| Protokoll | Codieren 


 a| 
Verknüpfen von S3-Vorgängen
 a| 
S3BK (S3-Bucket) und/oder S3KY (S3-Schlüssel)



 a| 
Swift-Vorgänge verknüpfen
 a| 
WCON (Swift-Container) und/oder WOBJ (Swift-Objekt)



 a| 
Verknüpfen interner Vorgänge
 a| 
CBID (interne Kennung des Objekts)

|===


== Timing von Audit-Meldungen

Aufgrund von Faktoren wie Zeitunterschieden zwischen Grid-Nodes, Objektgröße und Netzwerkverzögerungen kann die Reihenfolge der durch die verschiedenen Services erzeugten Audit-Meldungen von den Beispielen in diesem Abschnitt abweichen.



== Konfiguration der Richtlinien für das Informationslebenszyklus-Management

Bei der ILM-Standardrichtlinie (Baseline 2 Copy) werden Objektdaten einmal für insgesamt zwei Kopien kopiert. Wenn die ILM-Richtlinie mehr als zwei Kopien erfordert, gibt es für jede zusätzliche Kopie einen zusätzlichen Satz von CBRE-, CBSE- und SCMT-Meldungen. Weitere Informationen zu ILM-Richtlinien finden Sie unter Informationen zum Managen von Objekten mit Information Lifecycle Management.



== Archiv-Nodes

Die Reihe von Meldungen, die beim Senden von Objektdaten an ein externes Archiv-Speichersystem generiert werden, ist ähnlich wie bei Storage-Nodes, es sei denn, es gibt keine SCMT-Meldung (Store Object Commit). Und die ATCE (Archive Object Store Begin) und ASCE (Archive Object Store End) Nachrichten werden für jede archivierte Kopie von Objektdaten generiert.

Die Reihe von Audit-Meldungen, die beim Abrufen von Objektdaten aus einem externen Archiv-Storage-System generiert werden, ähnelt der für Storage-Nodes, jedoch werden für jede abgerufene Kopie von Objektdaten ARCB (Archivobjekt Retrieve Begin) und ARCE (Archive Object Retrieve End) Nachrichten generiert.

Die beim Löschen von Objektdaten aus einem externen Archivspeichersystem generierte Reihe von Überwachungsmeldungen ähnelt der für Speicherknoten, es sei denn, ES gibt keine SREM (Object Store Remove)-Nachricht und für jede Löschanforderung gibt es eine AREM-Nachricht (Archive Object Remove).

xref:../ilm/index.adoc[Objektmanagement mit ILM]
