---
permalink: audit/wput-swift-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WPUT, Swift PUT 
summary: Wenn ein Swift-Client eine PUT-Transaktion ausgibt, wird eine Anfrage zum Erstellen eines neuen Objekts oder Containers gestellt. Diese Meldung wird vom Server ausgegeben, wenn die Transaktion erfolgreich ist. 
---
= WPUT: Schnell AUSGEDRÜCKT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Swift-Client eine PUT-Transaktion ausgibt, wird eine Anfrage zum Erstellen eines neuen Objekts oder Containers gestellt. Diese Meldung wird vom Server ausgegeben, wenn die Transaktion erfolgreich ist.

|===
| Codieren | Feld | Beschreibung 


 a| 
CBID
 a| 
Kennung Für Inhaltsblock
 a| 
Die eindeutige Kennung des angeforderten Inhaltsblocks. Wenn die CBID unbekannt ist, ist dieses Feld auf 0 gesetzt. Dieses Feld wird nicht von den Operationen in Containern berücksichtigt.



 a| 
CSIZ
 a| 
Inhaltsgröße
 a| 
Die Größe des abgerufenen Objekts in Byte. Dieses Feld wird nicht von den Operationen in Containern berücksichtigt.



 a| 
HTRH
 a| 
HTTP-Anforderungskopf
 a| 
Liste der während der Konfiguration ausgewählten Namen und Werte für protokollierte HTTP-Anfragen.

*Hinweis:* `X-Forwarded-For` Wird automatisch einbezogen, wenn sie in der Anfrage vorhanden ist und wenn der `X-Forwarded-For` Der Wert unterscheidet sich von der IP-Adresse des Anforderungssenders (Feld SAIP-Audit).



 a| 
MTME
 a| 
Uhrzeit Der Letzten Änderung
 a| 
Der Unix-Zeitstempel in Mikrosekunden, der angibt, wann das Objekt zuletzt geändert wurde.



 a| 
RSLT
 a| 
Ergebniscode
 a| 
Ergebnis der PUT-Transaktion. Das Ergebnis ist immer:

ERFOLGREICH



 a| 
SAIP
 a| 
IP-Adresse des anfragenden Clients
 a| 
Die IP-Adresse der Client-Anwendung, die die Anforderung gestellt hat.



 a| 
ZEIT
 a| 
Zeit
 a| 
Gesamtbearbeitungszeit für die Anfrage in Mikrosekunden.



 a| 
TLIP
 a| 
Vertrauenswürdige Load Balancer-IP-Adresse
 a| 
Wenn die Anforderung von einem vertrauenswürdigen Layer 7 Load Balancer weitergeleitet wurde, ist die IP-Adresse des Load Balancer.



 a| 
UUID
 a| 
Universell Eindeutige Kennung
 a| 
Die Kennung des Objekts im StorageGRID System.



 a| 
WACC
 a| 
Swift Konto-ID
 a| 
Die eindeutige Konto-ID, die vom StorageGRID System festgelegt wurde.



 a| 
WOW
 a| 
Swift Container
 a| 
Der Swift-Containername.



 a| 
WOBJ
 a| 
Swift Objekt
 a| 
Die Swift Objekt-ID. Dieses Feld wird nicht von den Operationen in Containern berücksichtigt.



 a| 
WUSR
 a| 
Swift-Account-Benutzer
 a| 
Der Swift-Account-Benutzername, der den Client, der die Transaktion ausführt, eindeutig identifiziert.

|===