---
settings:
  name: StorageGRID
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.6 Dokumentation
    url: "/index.html"
  - section: release-notes
  - title: Los geht's
    entries:
    - section: primer
    - section: network
  - title: Installation und Wartung von Appliance-Hardware
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Installation und Upgrade von Software
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Durchführung der Systemadministration
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Verwenden Sie StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Überwachung und Wartung von StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Aktivieren Sie StorageGRID
    url: "/storagegrid-enable.html"
  - title: Frühere Versionen
    url: "/earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: "/release-notes/index.html"
    - title: Was ist neu
      url: "/upgrade/whats-new.html"
    - title: Gittergrundierung
      url: "/primer/index.html"
    - title: Netzwerkrichtlinien
      url: "/network/index.html"
  - title: Hardware warten
    links:
    - title: SG100- und SG1000-Services-Appliances
      url: "/sg100-1000/index.html"
    - title: SG6000 Storage-Appliances
      url: "/sg6000/index.html"
    - title: SG5700 Storage-Appliances
      url: "/sg5700/index.html"
    - title: SG5600 Storage Appliances
      url: "/sg5600/index.html"
  - title: Installieren Sie die Upgrade-Software
    links:
    - title: Installieren Sie Red hat Enterprise Linux oder CentOS
      url: "/rhel/index.html"
    - title: Installieren Sie Ubuntu oder Debian
      url: "/ubuntu/index.html"
    - title: VMware installieren
      url: "/vmware/index.html"
    - title: Software-Upgrade
      url: "/upgrade/index.html"
  - title: Konfigurieren des Grids
    links:
    - title: StorageGRID verwalten
      url: "/admin/index.html"
    - title: Objektmanagement mit ILM
      url: "/ilm/index.html"
    - title: Systemhärtung
      url: "/harden/index.html"
    - title: Konfigurieren Sie StorageGRID für FabricPool
      url: "/fabricpool/index.html"
  - title: Verwalten von Objekten
    links:
    - title: Verwenden Sie ein Mandantenkonto
      url: "/tenant/index.html"
    - title: S3 verwenden
      url: "/s3/index.html"
    - title: Verwenden Sie Swift
      url: "/swift/index.html"
  - title: Monitor-Wartung
    links:
    - title: Überwachung der Fehlerbehebung
      url: "/monitor/index.html"
    - title: Erweitern Sie Ihr Raster
      url: "/expand/index.html"
    - title: Recovery-Wartung
      url: "/maintain/index.html"
    - title: Prüfung von Audit-Protokollen
      url: "/audit/index.html"
  - title: Demos Tutorials
    links:
    - title: Informationen zur Aktivierung von StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: StorageGRID-Videobibliothek
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: NetApp Learning Services
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Mehr Ressourcen
    links:
    - title: StorageGRID Support-Seite
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: NetApp Interoperabilitäts-Matrix-Tool (IMT)
      url: https://mysupport.netapp.com/matrix
    - title: StorageGRID Knowledge Base
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: NetApp Blog
      url: https://netapp.com/blog/
    - title: NetApp Community
      url: https://community.netapp.com/
  - title: Frühere Versionen
    links:
    - title: StorageGRID 11.5-Dokumentation
      url: https://docs.netapp.com/sgws-115/index.jsp
    - title: StorageGRID 11.4-Dokumentation
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: StorageGRID 11.3-Dokumentation
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: StorageGRID 11.2-Dokumentation
      url: https://docs.netapp.com/sgws-112/index.jsp
