---
permalink: upgrade/impact-of-upgrade-on-groups-and-user-accounts.html 
sidebar: sidebar 
keywords: upgrade, permissions 
summary: Sie müssen die Auswirkungen des StorageGRID Upgrades kennen, damit Sie Gruppen und Benutzerkonten nach Abschluss des Upgrades entsprechend aktualisieren können. 
---
= Auswirkungen eines Upgrades auf Gruppen und Benutzerkonten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Auswirkungen des StorageGRID Upgrades kennen, damit Sie Gruppen und Benutzerkonten nach Abschluss des Upgrades entsprechend aktualisieren können.



== Änderungen an Gruppenberechtigungen und -Optionen

Nach dem Upgrade auf StorageGRID 11.6 können Sie optional die folgenden aktualisierten oder neuen Berechtigungen und Optionen (*KONFIGURATION* *Zugriffskontrolle* *Admin-Gruppen*) auswählen.

[cols="1a,2a"]
|===
| Berechtigung oder Option | Beschreibung 


 a| 
Mandantenkonten
 a| 
Diese Berechtigung erlaubt Benutzern nicht nur, Mandantenkonten zu erstellen, zu bearbeiten und zu entfernen, sondern ermöglicht es Administratoren nun auch, vorhandene Richtlinien für die Verkehrsklassifizierung (*KONFIGURATION* *Netzwerk* *Verkehrsklassifizierung*) anzuzeigen.

|===
Siehe xref:../admin/managing-admin-groups.adoc[Managen von Admin-Gruppen].
