---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID System auf eine neue Version zu aktualisieren. 
---
= Upgrade der StorageGRID Software: Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID System auf eine neue Version zu aktualisieren.



== Informationen zu diesen Anweisungen

Sie beschreiben die Neuerungen in StorageGRID 11.6 und bieten Schritt-für-Schritt-Anleitungen für das Upgrade aller Nodes in Ihrem StorageGRID System auf die neue Version.



== Bevor Sie beginnen

In diesen Themen erfahren Sie mehr über die neuen Funktionen und Verbesserungen in StorageGRID 11.6. Sie können ermitteln, ob Funktionen veraltet oder entfernt wurden, und informieren Sie sich über Änderungen an StorageGRID APIs.

* xref:whats-new.adoc[Die Neuheiten in StorageGRID 11.6]
* xref:removed-or-deprecated-features.adoc[Funktionen entfernt oder veraltet]
* xref:changes-to-grid-management-api.adoc[Änderungen an der Grid-Management-API]
* xref:changes-to-tenant-management-api.adoc[Änderungen an der Mandantenmanagement-API]

