---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords: features, removed, deprecated 
summary: Einige Funktionen wurden in dieser Version entfernt oder veraltet. Überprüfen Sie diese Elemente, um zu verstehen, ob Sie Clientanwendungen aktualisieren oder Ihre Konfiguration vor dem Upgrade ändern müssen. 
---
= Funktionen entfernt oder veraltet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einige Funktionen wurden in dieser Version entfernt oder veraltet. Überprüfen Sie diese Elemente, um zu verstehen, ob Sie Clientanwendungen aktualisieren oder Ihre Konfiguration vor dem Upgrade ändern müssen.



== Alarmsystem und alarmbasierte APIs sind veraltet

Ab Version StorageGRID 11.6 ist das veraltete Alarmsystem veraltet. Die Benutzeroberfläche und APIs für das alte Alarmsystem werden in einer zukünftigen Version entfernt.


IMPORTANT: Wenn Sie nach dem Upgrade auf StorageGRID 11.6 noch ältere Alarme verwenden, planen Sie einen vollständigen Übergang auf das Alarmsystem. Siehe xref:../monitor/managing-alerts-and-alarms.adoc[Alarme und Alarme verwalten: Übersicht] Um mehr über Warnungen zu erfahren.

Die Version 11.6 depretiert alle Alarm-basierten APIs. Die folgenden APIs sind von dieser Änderung betroffen:

* `GET /grid/alarms`: Völlig veraltet
* `GET /grid/health/topology`: Völlig veraltet
* `GET /grid/health`: Das `alarm-counts` Der Abschnitt der Antwort ist veraltet




== Zukünftige Versionen unterstützen keine maximale Objektgröße von 5 tib für PUT Objekt

In künftigen Versionen von StorageGRID beträgt die maximale Größe für einen einzelnen PUT-Objektvorgang 5 gib, anstatt 5 tib. Sie können für Objekte, die größer als 5 gib sind, mehrere Teile hochladen, bis zu maximal 5 tib (5,497,558,138,880 Byte).

Damit Sie Clients auf kleinere Objektgrößen in PUT Object umstellen können, wird in StorageGRID 11.6 die Warnmeldung *S3 PUT Objektgröße zu groß* ausgelöst, wenn ein S3-Client versucht, ein Objekt hochzuladen, das mehr als 5 gib beträgt.



== Die NAS-Bridge-Funktion ist veraltet

Die NAS Bridge-Funktion hatte bereits seit StorageGRID Version 11.4 eingeschränkten Zugriff. Die NAS Bridge-Funktion bleibt nur eingeschränkt verfügbar und ist ab StorageGRID 11.6 veraltet.

NAS-Bridge 11.4 bleibt das finale Release und wird weiterhin mit StorageGRID 11.6 kompatibel sein. Überprüfen Sie die https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Für die weitere Kompatibilität zwischen NAS Bridge 11.4 und StorageGRID Versionen.

Auf der NetApp Support Site finden Sie Informationen zu den https://mysupport.netapp.com/site/info/version-support["Support-Zeitplan für NAS Bridge"^].
