---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Bevor Sie mit dem Upgrade beginnen, müssen Sie überprüfen, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist. 
---
= Überprüfen Sie die installierte StorageGRID-Version
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit dem Upgrade beginnen, müssen Sie überprüfen, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist.

Bevor Sie ein Upgrade auf StorageGRID 11.6 durchführen, muss StorageGRID 11.5 installiert sein. Wenn Sie derzeit eine ältere Version von StorageGRID verwenden, müssen Sie alle früheren Upgrade-Dateien zusammen mit ihren neuesten Hotfixes installieren (dringend empfohlen), bis die aktuelle Version Ihres Rasters StorageGRID 11.5._x.y_ ist.

Ein möglicher Upgrade-Pfad wird im angezeigt  Upgrade to StorageGRID 11.5 from version 11.3.0.8,Beispiel.


IMPORTANT: NetApp empfiehlt dringend, vor dem Upgrade auf die nächste Version den aktuellen Hotfix für jede StorageGRID-Version anzuwenden und den aktuellen Hotfix für jede installierte neue Version anzuwenden. In einigen Fällen müssen Sie einen Hotfix anwenden, um das Risiko eines Datenverlusts zu vermeiden. Siehe https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] Und die Release Notes für jeden Hotfix, um mehr zu erfahren.

Beachten Sie, dass Sie in einem Schritt ein Skript zur Aktualisierung von 11.3.0.13+ auf 11.4.0._y_ und von 11.4.0.7+ bis 11.5.0._y_ ausführen können. Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp Knowledge Base: So führen Sie umfassende Upgrades und Hotfix-Skripte für StorageGRID aus"^].

.Schritte
. Melden Sie sich mit einem bei Grid Manager an xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
. Wählen Sie oben im Grid Manager die Option *Hilfe* *Info*.
. Vergewissern Sie sich, dass *Version* 11.5._x.y_ ist.
+
In der StorageGRID 11.5._x.y_ Versionsnummer:

+
** Die *Hauptversion* hat einen _x_-Wert von 0 (11.5.0).
** Ein *Hotfix*, wenn man angewendet wurde, hat einen _y_-Wert (z.B. 11.5.0.1).


. Wenn *Version* nicht 11.5._x.y_ ist, gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] So laden Sie die Dateien für jede vorherige Version herunter, einschließlich des neuesten Hotfix für jede Version.
. Lesen Sie die Upgrade-Anweisungen für jede heruntergeladene Version. Führen Sie dann das Software-Upgrade-Verfahren für dieses Release durch, und wenden Sie den neuesten Hotfix für dieses Release an (dringend empfohlen).
+
Siehe xref:../maintain/storagegrid-hotfix-procedure.adoc[StorageGRID Hotfix Verfahren].





== Beispiel: Upgrade auf StorageGRID 11.5 von Version 11.3.0.8

Das folgende Beispiel zeigt die Schritte zur Aktualisierung von StorageGRID Version 11.3.0.8 auf Version 11.5, um ein Upgrade auf StorageGRID 11.6 vorzubereiten.


IMPORTANT: Optional können Sie ein Skript ausführen, um die Schritte 2 und 3 (Update von 11.3.0.13+ auf 11.4.0._y_) zu kombinieren und die Schritte 4 und 5 zu kombinieren (Aktualisierung von 11.4.0.7+ auf 11.5.0._y_). Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp Knowledge Base: So führen Sie umfassende Upgrades und Hotfix-Skripte für StorageGRID aus"^].

Laden Sie die Software in der folgenden Reihenfolge herunter und installieren Sie sie, um Ihr System auf die Aktualisierung vorzubereiten:

. Wenden Sie den aktuellen StorageGRID 11.3.0._y_ Hotfix an.
. Upgrade auf StorageGRID 11.4.0 Hauptversion.
. Wenden Sie den aktuellen StorageGRID 11.4.0._y_ Hotfix an.
. Upgrade auf StorageGRID 11.5.0 Hauptversion.
. Wenden Sie den aktuellen StorageGRID 11.5.0._y_ Hotfix an.

