---
permalink: ubuntu/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: Überprüfen und konfigurieren Sie vor dem Installieren der StorageGRID Software die Hardware so, dass sie zur Unterstützung des StorageGRID Systems bereit ist. 
---
= CPU- und RAM-Anforderungen erfüllt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen und konfigurieren Sie vor dem Installieren der StorageGRID Software die Hardware so, dass sie zur Unterstützung des StorageGRID Systems bereit ist.

Weitere Informationen zu unterstützten Servern finden Sie in der Interoperabilitäts-Matrix.

Jeder StorageGRID Node benötigt die folgenden Mindestanforderungen:

* CPU-Cores: 8 pro Node
* RAM: Mindestens 24 GB pro Node und 2 bis 16 GB weniger als der gesamte System-RAM, abhängig von der verfügbaren RAM-Gesamtkapazität und der Anzahl der nicht-StorageGRID-Software, die auf dem System ausgeführt wird


Stellen Sie sicher, dass die Anzahl der StorageGRID-Knoten, die Sie auf jedem physischen oder virtuellen Host ausführen möchten, die Anzahl der CPU-Kerne oder des verfügbaren physischen RAM nicht überschreitet. Wenn die Hosts nicht dediziert für die Ausführung von StorageGRID sind (nicht empfohlen), sollten Sie die Ressourcenanforderungen der anderen Applikationen berücksichtigen.


IMPORTANT: Überwachen Sie Ihre CPU- und Arbeitsspeicherauslastung regelmäßig, um sicherzustellen, dass diese Ressourcen Ihre Workloads weiterhin erfüllen. Beispielsweise würde eine Verdoppelung der RAM- und CPU-Zuweisung für virtuelle Storage-Nodes ähnliche Ressourcen bereitstellen wie für die StorageGRID Appliance-Nodes. Wenn die Menge der Metadaten pro Node 500 GB überschreitet, sollten Sie darüber hinaus den RAM pro Node auf 48 GB oder mehr erhöhen. Informationen zum Management von Objekt-Metadaten-Storage, zum Erhöhen der Einstellung für reservierten Speicherplatz und zum Monitoring der CPU- und Arbeitsspeicherauslastung finden Sie in den Anweisungen für die Administration, das Monitoring und das Upgrade von StorageGRID.

Wenn Hyper-Threading auf den zugrunde liegenden physischen Hosts aktiviert ist, können Sie 8 virtuelle Kerne (4 physische Kerne) pro Node bereitstellen. Wenn Hyperthreading auf den zugrunde liegenden physischen Hosts nicht aktiviert ist, müssen Sie 8 physische Kerne pro Node bereitstellen.

Wenn Sie Virtual Machines als Hosts verwenden und die Größe und Anzahl der VMs kontrollieren können, sollten Sie für jeden StorageGRID Node eine einzelne VM verwenden und die Größe der VM entsprechend festlegen.

Bei Produktionsimplementierungen sollten nicht mehrere Storage-Nodes auf derselben physischen Speicherhardware oder einem virtuellen Host ausgeführt werden. Jeder Storage-Node in einer einzelnen StorageGRID-Implementierung sollte sich in einer eigenen, isolierten Ausfall-Domäne befinden. Sie können die Langlebigkeit und Verfügbarkeit von Objektdaten maximieren, wenn sichergestellt wird, dass ein einzelner Hardwareausfall nur einen einzelnen Storage-Node beeinträchtigen kann.

Siehe auch die Informationen über Speicheranforderungen.

.Verwandte Informationen
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]

xref:storage-and-performance-requirements.adoc[Storage- und Performance-Anforderungen erfüllt]

xref:../admin/index.adoc[StorageGRID verwalten]

xref:../monitor/index.adoc[Monitoring und Fehlerbehebung]

xref:../upgrade/index.adoc[Software-Upgrade]
