---
permalink: network/index.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: Mithilfe dieser Richtlinien lernen Sie die StorageGRID Architektur und Netzwerktopologien kennen und erfahren Sie mehr über die Anforderungen für Netzwerkkonfiguration und Provisionierung. 
---
= Netzwerkrichtlinien: Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe dieser Richtlinien lernen Sie die StorageGRID Architektur und Netzwerktopologien kennen und erfahren Sie mehr über die Anforderungen für Netzwerkkonfiguration und Provisionierung.



== Informationen zu diesen Anweisungen

Diese Richtlinien stellen Informationen bereit, die zum Erstellen der StorageGRID Netzwerkinfrastruktur vor der Bereitstellung und Konfiguration von StorageGRID Nodes verwendet werden können. Verwenden Sie diese Richtlinien, um sicherzustellen, dass die Kommunikation zwischen allen Knoten im Netz und zwischen dem Netz und externen Clients und Diensten erfolgen kann.

Externe Clients und externe Services müssen eine Verbindung zu StorageGRID-Netzwerken herstellen, um Funktionen wie die folgenden auszuführen:

* Speichern und Abrufen von Objektdaten
* Benachrichtigungen erhalten
* Zugriff auf die StorageGRID Management-Schnittstelle (Grid Manager und MandantenManager)
* Zugriff auf die Revisionsfreigabe (optional)
* Die Bereitstellung von Services wie:
+
** Network Time Protocol (NTP)
** Domain Name System (DNS)
** Verschlüsselungsmanagement-Server (KMS)




StorageGRID-Netzwerke müssen entsprechend konfiguriert werden, um den Datenverkehr für diese Funktionen und vieles mehr zu verarbeiten.



== Bevor Sie beginnen

Die Konfiguration des Netzwerks für ein StorageGRID System erfordert eine hohe Erfahrung mit Ethernet-Switching, TCP/IP-Netzwerken, Subnetzen, Netzwerk-Routing und Firewalls.

Bevor Sie das Netzwerk konfigurieren, machen Sie sich mit der StorageGRID Architektur vertraut, wie in beschrieben xref:../primer/index.adoc[Gittergrundierung].

Nachdem Sie festgelegt haben, welche StorageGRID-Netzwerke Sie verwenden möchten und wie diese Netzwerke konfiguriert werden sollen, können Sie die StorageGRID-Nodes installieren und konfigurieren, indem Sie die entsprechenden Anweisungen befolgen.

.Installation softwarebasierter Nodes
* xref:../rhel/index.adoc[Installieren Sie Red hat Enterprise Linux oder CentOS]
* xref:../ubuntu/index.adoc[Installieren Sie Ubuntu oder Debian]
* xref:../vmware/index.adoc[VMware installieren]


.Installieren Sie Appliance-Knoten
* xref:../sg100-1000/index.adoc[SG100- und SG1000-Services-Appliances]
* xref:../sg6000/index.adoc[SG6000 Storage-Appliances]
* xref:../sg5700/index.adoc[SG5700 Storage-Appliances]
* xref:../sg5600/index.adoc[SG5600 Storage Appliances]


.StorageGRID Software konfigurieren und verwalten
* xref:../admin/index.adoc[StorageGRID verwalten]
* xref:../release-notes/index.adoc[Versionshinweise]

