---
permalink: sg5600/automating-appliance-installation-and-configuration.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, automate, automating, automation, automatic, install, installation, configuration, configure 
summary: Sie können die Installation und Konfiguration Ihrer Appliances und die Konfiguration des gesamten StorageGRID Systems automatisieren. 
---
= Automatische Installation und Konfiguration der Appliance (SG5600)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Installation und Konfiguration Ihrer Appliances und die Konfiguration des gesamten StorageGRID Systems automatisieren.

Eine Automatisierung von Installation und Konfiguration kann sich bei der Implementierung mehrerer StorageGRID Instanzen oder einer großen, komplexen StorageGRID Instanz als nützlich erweisen.

Um Installation und Konfiguration zu automatisieren, verwenden Sie eine oder mehrere der folgenden Optionen:

* Erstellen Sie eine JSON-Datei, in der die Konfigurationseinstellungen für Ihre Appliances angegeben sind. Laden Sie die JSON-Datei mithilfe des StorageGRID-Appliance-Installationsprogramms hoch.
+

NOTE: Sie können dieselbe Datei verwenden, um mehr als ein Gerät zu konfigurieren.

* Verwenden Sie die StorageGRID``configure-sga.py`` Python-Skript zur Automatisierung der Konfiguration Ihrer Appliances.
* Zusätzliche Python-Skripte verwenden, um andere Komponenten des gesamten StorageGRID-Systems (das „Grid“) zu konfigurieren.



NOTE: StorageGRID-Automatisierungs-Python-Skripte können direkt verwendet werden oder als Beispiele für die Verwendung der StorageGRID Installations-REST-API in Grid-Implementierungs- und Konfigurations-Tools, die Sie selbst entwickeln. Weitere Informationen finden Sie unter xref:../maintain/gathering-required-materials-for-grid-node-recovery.adoc#download-and-extract-install-files-recover[Herunterladen und Extrahieren der StorageGRID-Installationsdateien].
