---
permalink: sg5600/gathering-installation-information-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: Bei der Installation und Konfiguration der StorageGRID Appliance sind Entscheidungen zu treffen und Informationen zu Ethernet Switch-Ports, IP-Adressen sowie zu Port- und Netzwerk-Bond-Modi zu sammeln. 
---
= Erfassen von Installationsinformationen (SG5600)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Installation und Konfiguration der StorageGRID Appliance sind Entscheidungen zu treffen und Informationen zu Ethernet Switch-Ports, IP-Adressen sowie zu Port- und Netzwerk-Bond-Modi zu sammeln.

.Über diese Aufgabe
Mithilfe der folgenden Tabellen können Sie Informationen für jedes Netzwerk, das Sie mit der Appliance verbinden, aufzeichnen. Diese Werte sind für die Installation und Konfiguration der Hardware erforderlich.



== Erforderliche Informationen für die Verbindung des E2700 Controllers mit dem SANtricity Storage Manager

Sie müssen den E2700 Controller mit dem Managementnetzwerk verbinden, das Sie für SANtricity Storage Manager verwenden.

|===
| Erforderliche Informationen | Ihr Wert 


 a| 
Ethernet-Switch-Port die Verbindung zum Management-Port 1 wird hergestellt
 a| 



 a| 
MAC-Adresse für Management-Port 1 (auf einem Etikett in der Nähe von Port P1 gedruckt)
 a| 



 a| 
Über DHCP zugewiesene IP-Adresse für Management-Port 1, sofern nach dem Einschalten verfügbar

*Hinweis:* Wenn das Netzwerk, das Sie mit dem E2700 Controller verbinden, einen DHCP-Server enthält, kann der Netzwerkadministrator die MAC-Adresse verwenden, um die vom DHCP-Server zugewiesene IP-Adresse zu ermitteln.
 a| 



 a| 
Geschwindigkeit und Duplexmodus

*Hinweis:* Sie müssen sicherstellen, dass der Ethernet-Switch für das SANtricity Storage Manager-Managementnetzwerk auf Autonegotiation gesetzt ist.
 a| 
Muss sein:

* Autonegotiation (Standard)




 a| 
IP-Adressformat
 a| 
Bitte auswählen:

* IPv4
* IPv6




 a| 
Statische IP-Adresse, die Sie für die Appliance im Managementnetzwerk verwenden möchten
 a| 
Für IPv4:

* IPv4-Adresse:
* Subnetzmaske:
* Gateway:


Für IPv6:

* IPv6-Adresse:
* Routingfähige IP-Adresse:
* E2700 Controller-Router-IP-Adresse:


|===


== Zum Anschließen des E5600SG-Controllers an das Admin-Netzwerk erforderliche Informationen

Das Admin-Netzwerk für StorageGRID ist ein optionales Netzwerk, das zur Systemadministration und -Wartung verwendet wird. Die Appliance stellt über die 1-GbE-Management-Ports des E5600SG-Controllers eine Verbindung zum Admin-Netzwerk her.

|===
| Erforderliche Informationen | Ihr Wert 


 a| 
Admin-Netzwerk aktiviert
 a| 
Bitte auswählen:

* Nein
* Ja (Standard)




 a| 
Netzwerk-Bond-Modus
 a| 
Bitte auswählen:

* Unabhängig
* Aktiv/Backup




 a| 
Switch-Port für Management-Port 1 (P1)
 a| 



 a| 
Switch-Port für Management Port 2 (P2; nur aktiv/Backup-Netzwerk-Bond-Modus)
 a| 



 a| 
MAC-Adresse für Management-Port 1 (auf einem Etikett in der Nähe von Port P1 gedruckt)
 a| 



 a| 
Über DHCP zugewiesene IP-Adresse für Management-Port 1, sofern nach dem Einschalten verfügbar

*Hinweis:* enthält das Admin-Netzwerk einen DHCP-Server, zeigt der E5600SG-Controller nach dem Start die DHCP-zugewiesene IP-Adresse auf seinem siebensegmentreichen Display an. Sie können auch die IP-Adresse bestimmen, die über DHCP zugewiesen wurde, indem Sie die MAC-Adresse verwenden, um die zugewiesene IP-Adresse zu ermitteln.
 a| 
* IPv4-Adresse (CIDR):
* Gateway:




 a| 
Statische IP-Adresse, die Sie für den Appliance-Speicherknoten im Admin-Netzwerk verwenden möchten

*Hinweis:* Wenn Ihr Netzwerk kein Gateway hat, geben Sie die gleiche statische IPv4-Adresse für das Gateway an.
 a| 
* IPv4-Adresse (CIDR):
* Gateway:




 a| 
Admin-Netzwerk-Subnetze (CIDR)
 a| 

|===


== Erforderliche Informationen zum Verbinden und Konfigurieren von 10-GbE-Ports auf dem E5600SG Controller

Die vier 10-GbE-Ports des E5600SG-Controllers verbinden das StorageGRID-Grid-Netzwerk und das Client-Netzwerk.


NOTE: Weitere Informationen zu den Optionen für diese Ports finden Sie unter „10-GbE-Portverbindungen für den E5600SG-Controller“.

|===
| Erforderliche Informationen | Ihr Wert 


 a| 
Port Bond-Modus
 a| 
Bitte auswählen:

* Fest (Standard)
* Aggregat




 a| 
Switch-Port für Port 1 (Client-Netzwerk für festen Modus)
 a| 



 a| 
Switch-Port für Port 2 (Grid-Netzwerk für Fixed-Modus)
 a| 



 a| 
Switch-Port für Port 3 (Client-Netzwerk für festen Modus)
 a| 



 a| 
Switch-Port für Port 4 (Grid-Netzwerk für Fixed-Modus)
 a| 

|===


== Zum Anschließen des E5600SG-Controllers an das Grid-Netzwerk erforderliche Informationen

Das Grid-Netzwerk für StorageGRID ist ein erforderliches Netzwerk, das für den gesamten internen StorageGRID-Datenverkehr verwendet wird. Die Appliance wird über die 10-GbE-Ports des E5600SG-Controllers mit dem Grid-Netzwerk verbunden.


NOTE: Weitere Informationen zu den Optionen für diese Ports finden Sie unter „10-GbE-Portverbindungen für den E5600SG-Controller“.

|===
| Erforderliche Informationen | Ihr Wert 


 a| 
Netzwerk-Bond-Modus
 a| 
Bitte auswählen:

* Aktiv/Backup (Standard)
* LACP (802.3ad)




 a| 
VLAN-Tagging aktiviert
 a| 
Bitte auswählen:

* Nein (Standard)
* Ja.




 a| 
VLAN-Tag (bei aktiviertem VLAN-Tagging)
 a| 
Geben Sie einen Wert zwischen 0 und 4095 ein:



 a| 
DHCP-zugewiesene IP-Adresse für das Grid-Netzwerk, sofern nach dem Einschalten verfügbar

*Hinweis:* enthält das Grid-Netzwerk einen DHCP-Server, zeigt der E5600SG-Controller nach dem Booten die DHCP-zugewiesene IP-Adresse für das Grid-Netzwerk auf seiner 7-Segment-Anzeige an.
 a| 
* IPv4-Adresse (CIDR):
* Gateway:




 a| 
Statische IP-Adresse, die Sie für den Appliance-Speicherknoten im Grid-Netzwerk verwenden möchten

*Hinweis:* Wenn Ihr Netzwerk kein Gateway hat, geben Sie die gleiche statische IPv4-Adresse für das Gateway an.
 a| 
* IPv4-Adresse (CIDR):
* Gateway:




 a| 
Grid-Netzwerknetze (CIDR)

*Hinweis:* Wenn das Client-Netzwerk nicht aktiviert ist, verwendet die Standardroute auf dem Controller das hier angegebene Gateway.
 a| 

|===


== Informationen zum Anschließen des E5600SG-Controllers an das Client-Netzwerk erforderlich

Das Client-Netzwerk für StorageGRID ist ein optionales Netzwerk, das Client-Protokollzugriff auf das Grid ermöglicht. Die Appliance wird über die 10-GbE-Ports des E5600SG-Controllers mit dem Client-Netzwerk verbunden.


NOTE: Weitere Informationen zu den Optionen für diese Ports finden Sie unter „10-GbE-Portverbindungen für den E5600SG-Controller“.

|===
| Erforderliche Informationen | Ihr Wert 


 a| 
Client-Netzwerk aktiviert
 a| 
Bitte auswählen:

* Nein (Standard)
* Ja.




 a| 
Netzwerk-Bond-Modus
 a| 
Bitte auswählen:

* Aktiv/Backup (Standard)
* LACP (802.3ad)




 a| 
VLAN-Tagging aktiviert
 a| 
Bitte auswählen:

* Nein (Standard)
* Ja.




 a| 
VLAN-Tag (bei aktiviertem VLAN-Tagging)
 a| 
Geben Sie einen Wert zwischen 0 und 4095 ein:



 a| 
DHCP-zugewiesene IP-Adresse für das Client-Netzwerk, falls nach dem Einschalten verfügbar
 a| 
* IPv4-Adresse (CIDR):
* Gateway:




 a| 
Statische IP-Adresse, die Sie für den Appliance-Speicherknoten im Client-Netzwerk verwenden möchten

*Hinweis:* Wenn das Client-Netzwerk aktiviert ist, verwendet die Standardroute auf dem Controller das hier angegebene Gateway.
 a| 
* IPv4-Adresse (CIDR):
* Gateway:


|===
.Verwandte Informationen
xref:reviewing-appliance-network-connections-sg5600.adoc[Appliance-Netzwerkverbindungen (SG5600) prüfen]

xref:configuring-hardware.adoc[Hardware konfigurieren (SG5600)]

xref:port-bond-modes-for-e5600sg-controller-ports.adoc[Port Bond-Modi für E5600SG Controller-Ports]
