---
permalink: sg5600/replacing-e5600sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, Replacing, replace, E5600sg, controller, remove, removing, removal, install, installing, installation 
summary: Möglicherweise müssen Sie den E5600SG-Controller austauschen. 
---
= E5600SG-Controller austauschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie den E5600SG-Controller austauschen.

.Was Sie benötigen
Sie müssen Zugriff auf die folgenden Ressourcen haben:

* Informationen zum Austausch der E-Series Hardware auf der NetApp Support-Website unter +http://["mysupport.netapp.com"^]
* E5600 Dokumentation auf der Support Site
* Das Gerät war xref:placing-appliance-into-maintenance-mode.adoc[In den Wartungsmodus versetzt].


.Über diese Aufgabe
Wenn beide Controller ausreichend funktionieren, um eine kontrollierte Abschaltung zu ermöglichen, können Sie zuerst den E5600SG Controller herunterfahren, um die Verbindung zum E2700 Controller zu unterbrechen.


NOTE: Wenn Sie den Controller vor dem Installieren der StorageGRID-Software ersetzen, können Sie nach Abschluss dieses Verfahrens möglicherweise nicht sofort auf den StorageGRID Appliance Installer zugreifen. Während Sie von anderen Hosts im selben Subnetz wie die Appliance auf das Installationsprogramm für StorageGRID-Geräte zugreifen können, können Sie nicht von Hosts in anderen Subnetzen darauf zugreifen. Diese Bedingung sollte sich innerhalb von 15 Minuten lösen (wenn Einträge im ARP-Cache für die ursprüngliche Controller-Zeit erforderlich sind), oder Sie können den Zustand sofort löschen, indem Sie alle alten ARP-Cacheeinträge manuell vom lokalen Router oder Gateway löschen.

.Schritte
. Verwenden Sie einen antistatischen Schutz.
. Beschriften Sie jedes Kabel, das an den E5600SG-Controller angeschlossen ist, damit Sie die Kabel korrekt wieder anschließen können.
+

IMPORTANT: Um eine verminderte Leistung zu vermeiden, dürfen die Kabel nicht verdreht, gefaltet, gequetscht oder treten. Die Kabel nicht enger als ein 5 cm (2 Zoll) Radius biegen.

. Wenn das Gerät in den Wartungsmodus versetzt wurde, schalten Sie den E5600SG-Controller aus.
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



.. Schalten Sie den E5600SG-Controller: + aus
`*shutdown -h now*`


. Schalten Sie das Gehäuse aus und warten Sie, bis alle LED- und siebenSegment-Anzeigeaktivitäten auf der Rückseite des Controllers angehalten sind.
. Entfernen Sie die Kabel.
. Entfernen Sie den Controller wie in der Dokumentation des E5600SG-Controllers beschrieben.
. Setzen Sie den neuen Controller ein, wie in der Dokumentation des E5600SG-Controllers beschrieben.
. Ersetzen Sie alle Kabel.
. Schalten Sie das Gehäuse wieder ein.
. Überwachen Sie die sieben-Segment-Codes.
+
** E2700 Controller:
+
Der endgültige LED-Status lautet `99`.

** E5600SG-Controller:
+
Der endgültige LED-Status lautet `HA`.



. Überwachen Sie den Status des Appliance Storage Node im Grid Manager.
+
Vergewissern Sie sich, dass die Appliance Storage Nodes den erwarteten Status aufweisen.



.Verwandte Informationen
https://["Verfahren zum Austausch von Hardware der NetApp E-Series und EF-Series"^]

http://["NetApp Dokumentation: E5600 Serie"^]
