---
permalink: sg5600/verifying-receipt-of-autosupport.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, verify, verification, verifying, confirm, confirmation, confirming, autosupport, auto-support, status 
summary: Sie sollten überprüfen, ob der technische Support Ihre AutoSupport Meldungen erhält. Den Status von AutoSupport für Ihre Systeme finden Sie im Active IQ Portal. Durch die Überprüfung des Eingangs dieser Nachrichten wird sichergestellt, dass der technische Support Ihre Informationen enthält, wenn Sie Hilfe benötigen. 
---
= Überprüfen Sie den Eingang von AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten überprüfen, ob der technische Support Ihre AutoSupport Meldungen erhält. Den Status von AutoSupport für Ihre Systeme finden Sie im Active IQ Portal. Durch die Überprüfung des Eingangs dieser Nachrichten wird sichergestellt, dass der technische Support Ihre Informationen enthält, wenn Sie Hilfe benötigen.

.Über diese Aufgabe
AutoSupport kann einen der folgenden Status anzeigen:

* *EIN*
+
Ein „EIN“-Status gibt an, dass der technische Support derzeit AutoSupport Meldungen vom System empfängt.

* *AUS*
+
Ein „OFF“-Status empfiehlt, dass Sie AutoSupport deaktiviert haben, da der technische Support in den letzten 15 Kalendertagen kein wöchentliches Protokoll vom System erhalten hat, oder es gab möglicherweise eine Änderung in Ihrer Umgebung oder Konfiguration (z. B.).

* *RÜCKGANG*
+
SIE haben den technischen Support benachrichtigt, dass Sie AutoSupport nicht aktivieren.



Nachdem der technische Support ein wöchentliches Protokoll aus dem System erhält, ändert sich der AutoSupport-Status in EIN.

.Schritte
. Wechseln Sie zur NetApp Support Site unter http://mysupport.netapp.com/["mysupport.netapp.com"^], Und melden Sie sich im Active IQ Portal.
. Wenn DER AutoSupport-Status NICHT AKTIVIERT ist und Sie der Meinung sind, dass er falsch ist, führen Sie Folgendes aus:
+
.. Überprüfen Sie die Systemkonfiguration, um sicherzustellen, dass AutoSupport aktiviert ist.
.. Überprüfen Sie Ihre Netzwerkumgebung und -Konfiguration, um sicherzustellen, dass das System Meldungen an den technischen Support senden kann.



