---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: Wenn Sie einen S3-Mandanten verwenden, können Sie mithilfe des Mandanten Manager oder der Mandanten-Management-API die Konsistenzkontrolle für Vorgänge ändern, die in den Objekten in S3 Buckets ausgeführt werden. 
---
= Ändern der Konsistenzstufe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen S3-Mandanten verwenden, können Sie mithilfe des Mandanten Manager oder der Mandanten-Management-API die Konsistenzkontrolle für Vorgänge ändern, die in den Objekten in S3 Buckets ausgeführt werden.

.Was Sie benötigen
* Sie müssen mit einem beim Mandantenmanager angemeldet sein xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie müssen einer Benutzergruppe angehören, die über die Berechtigung Alle Buckets verwalten oder Root Access verfügt. Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien. Siehe xref:tenant-management-permissions.adoc[Mandantenmanagement-Berechtigungen].


.Über diese Aufgabe
Die Konsistenzstufe sorgt für einen Kompromiss zwischen der Verfügbarkeit der Objekte und der Konsistenz dieser Objekte über verschiedene Speicherknoten und Standorte hinweg. Im Allgemeinen sollten Sie für Ihre Buckets die Konsistenzstufe *Read-after-New-write* verwenden. Wenn die Konsistenzstufe *Read-after-New-write* nicht den Anforderungen der Client-Anwendung entspricht, können Sie die Konsistenzstufe ändern, indem Sie die Bucket-Konsistenzstufe oder die verwenden `Consistency-Control` Kopfzeile. Der `Consistency-Control` Kopfzeile setzt die Bucket-Konsistenzstufe außer Kraft.


NOTE: Wenn Sie die Konsistenzstufe eines Buckets ändern, werden nur die Objekte, die nach der Änderung aufgenommen werden, garantiert, um die überarbeitete Ebene zu erfüllen.

.Schritte
. Wählen Sie *STORAGE (S3)* *Buckets* aus.
. Wählen Sie den Bucket-Namen aus der Liste aus.
+
Die Seite mit den Bucket-Details wird angezeigt.

. Wählen Sie *Bucket-Optionen* *Konsistenzstufe* aus.
. Wählen Sie eine Konsistenzstufe für Operationen aus, die an den Objekten in diesem Bucket durchgeführt werden.
+
[cols="1a,3a"]
|===
| Konsistenzstufe | Beschreibung 


 a| 
Alle
 a| 
Alle Nodes erhalten die Daten sofort, sonst schlägt die Anfrage fehl.



 a| 
Stark global
 a| 
Garantierte Konsistenz bei Lese-nach-Schreibvorgängen für alle Client-Anfragen an allen Standorten.



 a| 
Stark vor Ort
 a| 
Garantiert Konsistenz bei Lese-nach-Schreibvorgängen für alle Client-Anfragen innerhalb eines Standorts.



 a| 
Read-after-New-Write (Standard)
 a| 
Ermöglicht Konsistenz von Lese- nach Schreibvorgängen für neue Objekte und die eventuelle Konsistenz von Objekt-Updates. Hochverfügbarkeit und garantierte Datensicherung Am ehesten entspricht die Konsistenzgarantie von Amazon S3.

*Hinweis:* Wenn Ihre Anwendung versucht, OPERATIONEN auf Schlüssel ZU ERHALTEN, die nicht existieren, setzen Sie die Consistency Level auf *available*, es sei denn, Sie benötigen Amazon S3 Consistency Garantien. Andernfalls kann eine hohe Anzahl von 500 internen Serverfehlern führen, wenn ein oder mehrere Speicherknoten nicht verfügbar sind.



 a| 
Verfügbar (eventuelle Konsistenz für HEAD- oder GET-Vorgänge)
 a| 
Verhält sich wie die Konsistenz *Read-after-New-write*, bietet aber schließlich Konsistenz für KOPF- und GET-Vorgänge. Bietet höhere Verfügbarkeit für HEAD und GET Operations als *Read-after-New-write* wenn Speicherknoten nicht verfügbar sind. Unterscheidet sich von Amazon S3 Konsistenzgarantien für HEAD- und GET-Operationen.

|===
. Wählen Sie *Änderungen speichern*.

