---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: Sie können neue Gruppen schneller erstellen, indem Sie eine vorhandene Gruppe duplizieren. 
---
= Gruppe duplizieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können neue Gruppen schneller erstellen, indem Sie eine vorhandene Gruppe duplizieren.

.Was Sie benötigen
* Sie müssen mit einem beim Mandantenmanager angemeldet sein xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie müssen einer Benutzergruppe mit Root Access-Berechtigung angehören. Siehe xref:tenant-management-permissions.adoc[Mandantenmanagement-Berechtigungen].


.Schritte
. Wählen Sie *ZUGRIFFSVERWALTUNG* *Gruppen*.
. Aktivieren Sie das Kontrollkästchen für die Gruppe, die Sie duplizieren möchten.
. Wählen Sie *Gruppe duplizieren*. Weitere Informationen zum Erstellen einer Gruppe finden Sie in den Anweisungen zum Erstellen von Gruppen für xref:creating-groups-for-s3-tenant.adoc[Einen S3-Mandanten] Oder für xref:creating-groups-for-swift-tenant.adoc[Einen Swift-Mandanten].
. Wählen Sie die Registerkarte *Lokale Gruppe* aus, um eine lokale Gruppe zu erstellen, oder wählen Sie die Registerkarte *Federated Group* aus, um eine Gruppe aus der zuvor konfigurierten Identitätsquelle zu importieren.
+
Wenn Single Sign-On (SSO) für Ihr StorageGRID-System aktiviert ist, können sich Benutzer, die zu lokalen Gruppen gehören, nicht beim Mandanten-Manager anmelden, obwohl sie mithilfe von Client-Applikationen die Ressourcen des Mandanten managen können, xref:tenant-management-permissions.adoc[Basierend auf Gruppenberechtigungen].

. Geben Sie den Namen der Gruppe ein.
+
** *Lokale Gruppe*: Geben Sie einen Anzeigenamen und einen eindeutigen Namen ein. Sie können den Anzeigenamen später bearbeiten.
** *Federated Group*: Geben Sie den eindeutigen Namen ein. Bei Active Directory ist der eindeutige Name der dem zugeordneten Name `sAMAccountName` Attribut. Bei OpenLDAP ist der eindeutige Name der Name, der dem zugeordnet ist `uid` Attribut.


. Wählen Sie *Weiter*.
. Ändern Sie bei Bedarf die Berechtigungen für diese Gruppe.
. Wählen Sie *Weiter*.
. Wenn Sie eine Gruppe für einen S3-Mandanten duplizieren, wählen Sie bei Bedarf aus den Optionsfeldern *S3-Richtlinie hinzufügen* eine andere Richtlinie aus. Wenn Sie eine benutzerdefinierte Richtlinie ausgewählt haben, aktualisieren Sie den JSON-String wie erforderlich.
. Wählen Sie *Gruppe erstellen*.

