---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Ein Mandantenkonto ermöglicht Ihnen, entweder die Simple Storage Service (S3) REST-API oder die Swift REST-API zu verwenden, um Objekte in einem StorageGRID System zu speichern und abzurufen.' 
---
= Verwenden Sie ein Mandantenkonto: Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Mandantenkonto ermöglicht Ihnen, entweder die Simple Storage Service (S3) REST-API oder die Swift REST-API zu verwenden, um Objekte in einem StorageGRID System zu speichern und abzurufen.



== Was ist ein Mandantenkonto?

Jedes Mandantenkonto verfügt über eigene föderierte bzw. lokale Gruppen, Benutzer, S3 Buckets oder Swift Container und Objekte.

Optional können Mandantenkonten verwendet werden, um gespeicherte Objekte nach verschiedenen Einheiten zu trennen. Beispielsweise können für einen der folgenden Anwendungsfälle mehrere Mandantenkonten verwendet werden:

* *Anwendungsbeispiel für Unternehmen:* Wenn das StorageGRID-System innerhalb eines Unternehmens verwendet wird, kann der Objekt-Storage des Grid von den verschiedenen Abteilungen des Unternehmens getrennt werden. Beispielsweise können Mandantenkonten für die Marketingabteilung, die Kundenbetreuung, die Personalabteilung usw. vorhanden sein.
+

NOTE: Wenn Sie das S3-Client-Protokoll verwenden, können Sie auch S3-Buckets und Bucket-Richtlinien verwenden, um Objekte zwischen den Abteilungen eines Unternehmens zu trennen. Sie müssen keine separaten Mandantenkonten erstellen. Siehe xref:../s3/index.adoc[Anweisungen zur Implementierung von S3-Client-Applikationen].

* *Anwendungsfall des Service-Providers:* Wenn das StorageGRID-System von einem Service-Provider verwendet wird, kann der Objekt-Storage des Grid von den verschiedenen Einheiten getrennt werden, die den Storage leasen. Beispielsweise können Mandantenkonten für Unternehmen A, Unternehmen B, Unternehmen C usw. vorhanden sein.




== Erstellen eines Mandantenkontos

Mandantenkonten werden von einem erstellt xref:../admin/managing-tenants.adoc[StorageGRID Grid-Administrator, der den Grid Manager verwendet]. Beim Erstellen eines Mandantenkontos gibt der Grid-Administrator die folgenden Informationen an:

* Anzeigename für den Mandanten (die Konto-ID des Mandanten wird automatisch zugewiesen und kann nicht geändert werden).
* Gibt an, ob das Mandantenkonto das S3 oder Swift verwenden wird
* Bei S3-Mandantenkonten: Unabhängig davon, ob das Mandantenkonto Plattform-Services nutzen darf. Wenn die Nutzung von Plattformdiensten zulässig ist, muss das Grid so konfiguriert werden, dass es seine Verwendung unterstützt.
* Optional: Ein Storage-Kontingent für das Mandantenkonto – die maximale Anzahl der Gigabyte, Terabyte oder Petabyte, die für die Mandantenobjekte verfügbar sind. Das Storage-Kontingent eines Mandanten stellt eine logische Menge (Objektgröße) und keine physische Menge (Größe auf der Festplatte) dar.
* Wenn die Identitätsföderation für das StorageGRID-System aktiviert ist, hat die föderierte Gruppe Root-Zugriffsberechtigungen, um das Mandantenkonto zu konfigurieren.
* Wenn Single Sign-On (SSO) nicht für das StorageGRID-System verwendet wird, gibt das Mandantenkonto seine eigene Identitätsquelle an oder teilt die Identitätsquelle des Grid mit, und zwar mit dem anfänglichen Passwort für den lokalen Root-Benutzer des Mandanten.


Grid-Administratoren können zudem die S3-Objektsperreneinstellung für das StorageGRID System aktivieren, wenn S3-Mandantenkonten die gesetzlichen Anforderungen erfüllen müssen. Wenn S3 Object Lock aktiviert ist, können alle S3-Mandantenkonten konforme Buckets erstellen und managen.



=== S3-Mandanten konfigurieren

Nach einem xref:../admin/creating-tenant-account.adoc[S3-Mandantenkonto wird erstellt], Sie können auf den Tenant Manager zugreifen, um Aufgaben wie die folgenden durchzuführen:

* Einrichten von Identitätsföderation (es sei denn, die Identitätsquelle wird gemeinsam mit dem Grid verwendet) oder Erstellen lokaler Gruppen und Benutzer
* Verwalten von S3-Zugriffsschlüsseln
* Erstellung und Management von S3 Buckets, einschließlich konformer Buckets
* Verwenden von Plattform-Services (falls aktiviert)
* Monitoring der Storage-Auslastung



IMPORTANT: Während Sie mit Tenant Manager S3-Buckets erstellen und managen können, sind Sie unbedingt erforderlich xref:../s3/index.adoc[S3-Zugriffsschlüssel und nutzen die S3-REST-API, um Objekte aufzunehmen und zu managen].



=== Konfigurieren Sie Swift Mandanten

Nach A xref:../admin/creating-tenant-account.adoc[Swift-Mandantenkonto wird erstellt], Sie können auf den Tenant Manager zugreifen, um Aufgaben wie die folgenden durchzuführen:

* Einrichten von Identitätsföderation (es sei denn, die Identitätsquelle wird gemeinsam mit dem Grid verwendet) und Erstellen lokaler Gruppen und Benutzer
* Monitoring der Storage-Auslastung



IMPORTANT: Swift-Benutzer müssen über die Root-Zugriffsberechtigung für den Zugriff auf den Mandanten-Manager verfügen. Die Root-Zugriffsberechtigung erlaubt Benutzern jedoch nicht, sich in dem zu authentifizieren xref:../swift/index.adoc[Swift REST API] Um Container zu erstellen und Objekte aufzunehmen. Benutzer müssen über die Swift-Administratorberechtigung verfügen, um sich bei der Swift-REST-API zu authentifizieren.



== Verwenden Sie Tenant Manager

Der Tenant Manager ermöglicht das Management aller Aspekte eines StorageGRID-Mandantenkontos.

Mit dem Mandanten-Manager lässt sich die Storage-Auslastung eines Mandantenkontos überwachen und Benutzer mit Identitätsföderation bzw. durch das Erstellen von lokalen Gruppen und Benutzern managen. Bei S3-Mandantenkonten können Sie auch S3-Schlüssel managen, S3-Buckets managen und Plattform-Services konfigurieren.
