---
permalink: tenant/tenant-management-api-versioning.html 
sidebar: sidebar 
keywords: tenant management api version 
summary: Die Mandanten-Management-API verwendet Versionierung zur Unterstützung unterbrechungsfreier Upgrades. 
---
= Mandantenmanagement-API-Versionierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Mandanten-Management-API verwendet Versionierung zur Unterstützung unterbrechungsfreier Upgrades.

Diese Anforderungs-URL gibt beispielsweise Version 3 der API an.

[listing]
----
https://hostname_or_ip_address/api/v3/authorize
----
Die Hauptversion der Mandantenmanagement-API wird angestoßen, wenn Änderungen vorgenommen werden, die mit älteren Versionen *_nicht kompatibel_* sind. Die Nebenversion der Mandantenmanagement-API wird angestoßen, wenn Änderungen vorgenommen werden, dass *_kompatibel_* mit älteren Versionen sind. Zu den kompatiblen Änderungen gehört das Hinzufügen neuer Endpunkte oder neuer Eigenschaften. Das folgende Beispiel zeigt, wie die API-Version basierend auf dem Typ der vorgenommenen Änderungen angestoßen wird.

[cols="2a,1a,1a"]
|===
| Typ der Änderung in API | Alte Version | Neue Version 


 a| 
Kompatibel mit älteren Versionen
 a| 
2.1
 a| 
2.2



 a| 
Nicht kompatibel mit älteren Versionen
 a| 
2.1
 a| 
3.0

|===
Wenn die StorageGRID-Software zum ersten Mal installiert wird, ist nur die neueste Version der Mandantenmanagement-API aktiviert. Wenn StorageGRID jedoch auf eine neue Funktionsversion aktualisiert wird, haben Sie weiterhin Zugriff auf die ältere API-Version für mindestens eine StorageGRID-Funktionsversion.

Veraltete Anfragen werden wie folgt als veraltet markiert:

* Der Antwortkopf ist "Deprecated: True"
* Der JSON-Antwortkörper enthält „veraltet“: Wahr




== Legen Sie fest, welche API-Versionen in der aktuellen Version unterstützt werden

Verwenden Sie die folgende API-Anforderung, um eine Liste der unterstützten API-Hauptversionen anzuzeigen:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Geben Sie die API-Version für die Anforderung an

Sie können die API-Version mithilfe eines Pfadparameters angeben (`/api/v3`) Oder eine Kopfzeile (`Api-Version: 3`). Wenn Sie beide Werte angeben, überschreibt der Kopfzeilenwert den Pfadwert.

[listing]
----
curl https://[IP-Address]/api/v3/grid/accounts

curl -H "Api-Version: 3" https://[IP-Address]/api/grid/accounts
----