---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: Bevor Sie Grid-Nodes implementieren und das StorageGRID Grid konfigurieren, müssen Sie die Schritte und Anforderungen für das Durchführen des Verfahrens kennen. 
---
= Vor der Installation (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Grid-Nodes implementieren und das StorageGRID Grid konfigurieren, müssen Sie die Schritte und Anforderungen für das Durchführen des Verfahrens kennen.

Bei den Implementierungs- und Konfigurationsverfahren für StorageGRID ist bereits die Architektur und die betrieblichen Funktionen des StorageGRID Systems bekannt.

Sie können einen oder mehrere Standorte gleichzeitig implementieren. Alle Standorte müssen jedoch die Mindestanforderungen erfüllen, die für mindestens drei Storage-Nodes bestehen.


IMPORTANT: StorageGRID unterstützt die Verwendung von Virtual Storage Area Networks (VSANs) nicht, da der zugrunde liegende Festplattenschutz keine Hardware-RAID ist.

Bevor Sie mit der Implementierung eines Node und der Grid-Konfiguration beginnen, müssen Sie:

* Planung der StorageGRID Implementierung
* Installation, Anschluss und Konfiguration der gesamten erforderlichen Hardware – einschließlich aller StorageGRID Appliances – gemäß den Spezifikationen
+

NOTE: Hardware-spezifische Installations- und Integrationsanweisungen sind nicht im Installationsverfahren für StorageGRID enthalten. Informationen zur Installation von StorageGRID Appliances finden Sie in der Installations- und Wartungsanleitung für Ihre Appliance.

* Verstehen Sie die xref:../network/index.adoc[Verfügbare Netzwerkoptionen und wie die einzelnen Netzwerkoptionen in Grid-Nodes implementiert werden sollen].
* Sammeln Sie alle Netzwerkinformationen im Voraus. Wenn Sie nicht DHCP verwenden, sammeln Sie die IP-Adressen, die jedem Grid-Node zugewiesen werden sollen, und die IP-Adressen des Domain Name System (DNS) und der von Ihnen verwendeten NTP-Server (Network Time Protocol).
* Legen Sie fest, welche der verfügbaren Implementierungs- und Konfigurationstools Sie verwenden möchten.


.Verwandte Informationen
xref:../sg100-1000/index.adoc[SG100- und SG1000-Services-Appliances]

xref:../sg6000/index.adoc[SG6000 Storage-Appliances]

xref:../sg5700/index.adoc[SG5700 Storage-Appliances]

xref:../sg5600/index.adoc[SG5600 Storage Appliances]
