---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: red hat linux installation files, how to download installation files 
summary: Sie müssen das StorageGRID-Installationsarchiv herunterladen und die erforderlichen Dateien extrahieren. 
---
= Laden Sie die StorageGRID Installationsdateien herunter und extrahieren Sie sie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das StorageGRID-Installationsarchiv herunterladen und die erforderlichen Dateien extrahieren.

.Schritte
. Wechseln Sie zum https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Download-Seite für StorageGRID"^].
. Wählen Sie die Schaltfläche zum Herunterladen der neuesten Version, oder wählen Sie eine andere Version aus dem Dropdown-Menü aus und wählen Sie *Go*.
. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Wenn eine Warnung/MusterLeseanweisung angezeigt wird, lesen Sie sie, und aktivieren Sie das Kontrollkästchen.
+

IMPORTANT: Nachdem Sie die StorageGRID Version installiert haben, müssen Sie alle erforderlichen Hotfixes anwenden. Weitere Informationen finden Sie im xref:../maintain/storagegrid-hotfix-procedure.adoc[Hotfix-Verfahren in der Recovery- und Wartungsanleitung].

. Lesen Sie die Endbenutzer-Lizenzvereinbarung, aktivieren Sie das Kontrollkästchen und wählen Sie dann *Weiter akzeptieren*.
. Wählen Sie in der Spalte *Install StorageGRID* die .tgz- oder .zip-Datei für Red hat Enterprise Linux oder CentOS aus.
+

NOTE: Wählen Sie die aus `.zip` Datei, wenn Windows auf dem Service-Laptop ausgeführt wird.

. Speichern und extrahieren Sie die Archivdatei.
. Wählen Sie aus der folgenden Liste die benötigten Dateien aus.
+
Die benötigten Dateien hängen von der geplanten Grid-Topologie und der Implementierung des StorageGRID Systems ab.

+

NOTE: Die in der Tabelle aufgeführten Pfade beziehen sich auf das Verzeichnis der obersten Ebene, das vom extrahierten Installationsarchiv installiert wird



[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./Effektivwert/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Effektivwert/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./Effektivwert/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM Paket für die Installation der StorageGRID Node Images auf Ihren RHEL- oder CentOS-Hosts.



| ./Effektivwert/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM Paket für die Installation des StorageGRID Host Service auf Ihren RHEL- oder CentOS-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Effektivwert/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Effektivwert/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./rpms/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./Effektivwert/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können.



| ./rpms/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript:



| ./rpms/Extras/ansible  a| 
Beispiel für die Ansible-Rolle und das Playbook zur Konfiguration von RHEL- oder CentOS-Hosts für die Implementierung von StorageGRID Containern Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./rpms/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie mit diesen Schemas bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung zum Testen der Upgrade-Kompatibilität besitzen.

|===