---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Jeder Node in Ihrem Raster verfügt über ein eindeutiges Node-Konsolenpasswort, das Sie sich beim Node einloggen müssen. Verwenden Sie diese Schritte, um das Passwort der Node-Konsole für jeden Node im Raster zu ändern. Die Passwörter werden im Wiederherstellungspaket gespeichert. 
---
= Ändern der Passwörter für die Node-Konsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Node in Ihrem Raster verfügt über ein eindeutiges Node-Konsolenpasswort, das Sie sich beim Node einloggen müssen. Verwenden Sie diese Schritte, um jedes eindeutige Node-Konsolenpasswort für jeden Node im Raster zu ändern.

.Was Sie benötigen
* Sie sind mit einem bei Grid Manager angemeldet link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die Berechtigung Wartung oder Stammzugriff.
* Sie haben die aktuelle Provisionierungs-Passphrase.


.Über diese Aufgabe
Verwenden Sie das Node-Konsolenpasswort, um sich mit SSH bei einem Knoten als „admin“ oder beim Root-Benutzer einer VM/physischen Konsolenverbindung anzumelden. Mit dem Passwort für die Änderungsknotenkonsole werden für jeden Knoten in der Tabelle neue Passwörter erstellt und die Passwörter in einem aktualisierten System gespeichert `Passwords.txt` Datei im Wiederherstellungspaket. Die Passwörter sind in der Spalte Kennwort im aufgeführt `Passwords.txt` Datei:


NOTE: Separate SSH-Zugriffskennwörter für die SSH-Schlüssel, die für die Kommunikation zwischen den Nodes verwendet werden. Die SSH-Zugriffskennwörter werden durch dieses Verfahren nicht geändert.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *KONFIGURATION* *Zugriffskontrolle* *Grid-Passwörter*.
. Wählen Sie unter *Change Node Console passwords* die Option *make a change* aus.




== Geben Sie die Provisionierungs-Passphrase ein

.Schritte
. Geben Sie die Provisionierungs-Passphrase für Ihr Grid ein.
. Wählen Sie *Weiter*.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie das aktuelle Wiederherstellungspaket herunter, bevor Sie die Kennwörter der Node-Konsole ändern. Sie können die Passwörter in dieser Datei verwenden, wenn die Passwortänderung für einen beliebigen Knoten fehlschlägt.

.Schritte
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaket-Datei (`.zip`) An zwei sichere und getrennte Stellen.
+

CAUTION: Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.

. Wählen Sie *Weiter*.
. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Yes* aus, wenn Sie bereit sind, die Kennwörter der Knotenkonsole zu ändern.
+
Sie können diesen Vorgang nach dem Start nicht abbrechen.





== Ändern der Passwörter für die Node-Konsole

Wenn der Kennwortprozess der Knotenkonsole gestartet wird, wird ein neues Wiederherstellungspaket erstellt, das die neuen Kennwörter enthält. Anschließend werden die Passwörter auf jedem Node aktualisiert.

.Schritte
. Warten Sie, bis das neue Wiederherstellungspaket erstellt wurde. Dies kann einige Minuten dauern.
. Wählen Sie *Neues Wiederherstellungspaket herunterladen*.
. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie das `.zip` Datei:
.. Bestätigen Sie, dass Sie auf den Inhalt zugreifen können, einschließlich `Passwords.txt` Datei, die die neuen Passwörter für die Node-Konsole enthält.
.. Kopieren Sie die neue Wiederherstellungspaket-Datei (`.zip`) An zwei sichere und getrennte Stellen.
+

CAUTION: Überschreiben Sie das alte Wiederherstellungspaket nicht.

+
Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.



. Aktivieren Sie das Kontrollkästchen, um anzugeben, dass Sie das neue Wiederherstellungspaket heruntergeladen und den Inhalt überprüft haben.
. Wählen Sie *Knotenkonsolenpasswörter ändern* und warten Sie, bis alle Knoten mit den neuen Kennwörtern aktualisiert werden. Dies kann einige Minuten dauern.
+
Wenn Passwörter für alle Nodes geändert werden, wird ein grünes Erfolgsbanner angezeigt. Fahren Sie mit dem nächsten Schritt fort.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, zeigt eine Bannermeldung die Anzahl der Knoten an, bei denen die Passwörter nicht geändert wurden. Das System wiederholt den Prozess automatisch auf jedem Knoten, bei dem das Kennwort nicht geändert wurde. Wenn der Prozess endet, wenn einige Knoten noch kein geändertes Kennwort haben, wird die Schaltfläche *Wiederholen* angezeigt.

+
Wenn die Kennwortaktualisierung für einen oder mehrere Knoten fehlgeschlagen ist:

+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Beheben Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+

NOTE: Beim erneuten Versuch werden nur die Kennwörter der Knotenkonsole auf den Knoten geändert, die bei früheren Kennwortänderungsversuchen fehlgeschlagen sind.



. Nachdem die Passwörter für die Node-Konsole für alle Nodes geändert wurden, löschen Sie die <<download-current,Erstes heruntergeladenes Wiederherstellungspaket>>.
. Verwenden Sie optional den Link *Recovery Package*, um eine zusätzliche Kopie des neuen Recovery Package herunterzuladen.

