---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: 'Es können HA-Gruppen (High Availability, Hochverfügbarkeit) verwendet werden, um hochverfügbare Verbindungen zu StorageGRID für Objektdaten und zur Verwendung durch den Administrator zur Verfügung zu stellen.' 
---
= Wie werden HA-Gruppen verwendet?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es können HA-Gruppen (High Availability, Hochverfügbarkeit) verwendet werden, um hochverfügbare Verbindungen zu StorageGRID für Objektdaten und zur Verwendung durch den Administrator zur Verfügung zu stellen.

* Eine HA-Gruppe kann hochverfügbare administrative Verbindungen mit dem Grid Manager oder dem Mandanten Manager bereitstellen.
* Eine HA-Gruppe kann hochverfügbare Datenverbindungen für S3 und Swift Clients bieten.
* Eine HA-Gruppe, die nur eine Schnittstelle enthält, ermöglicht es Ihnen, viele VIP-Adressen bereitzustellen und explizit IPv6-Adressen festzulegen.


Eine HA-Gruppe kann nur Hochverfügbarkeit bieten, wenn alle Nodes in der Gruppe dieselben Services bereitstellen. Wenn Sie eine HA-Gruppe erstellen, fügen Sie Schnittstellen von den Typen von Nodes hinzu, die die erforderlichen Services bereitstellen.

* *Admin Nodes*: Schließen Sie den Load Balancer Service ein und ermöglichen Sie den Zugriff auf den Grid Manager oder den Tenant Manager.
* *Gateway-Knoten*: Schließen Sie den Load Balancer Service und den CLB-Dienst (veraltet) ein.


[cols="1a,2a"]
|===
| Zweck der HA-Gruppe | Fügen Sie diesem Typ Nodes der HA-Gruppe hinzu 


 a| 
Zugriff auf Grid Manager
 a| 
* Primärer Admin-Node (*Primär*)
* Nicht primäre Admin-Nodes


*Hinweis:* der primäre Admin-Knoten muss die primäre Schnittstelle sein. Einige Wartungsvorgänge können nur vom primären Admin-Node ausgeführt werden.



 a| 
Zugriff nur auf Tenant Manager
 a| 
* Primäre oder nicht primäre Admin-Nodes




 a| 
S3- oder Swift-Client-Zugriff – Load Balancer Service
 a| 
* Admin-Nodes
* Gateway-Nodes




 a| 
S3-Client-Zugriff für xref:../admin/manage-s3-select-for-tenant-accounts.adoc[S3 Select]
 a| 
* SG100- oder SG1000-Appliances
* VMware-basierte Software-Nodes


*Hinweis*: HA-Gruppen werden bei der Verwendung von S3 Select empfohlen, aber nicht erforderlich.



 a| 
S3- oder Swift-Client-Zugriff -- CLB-Service

*Hinweis:* der CLB-Service ist veraltet.
 a| 
* Gateway-Nodes


|===


== Einschränkungen bei der Verwendung von HA-Gruppen mit Grid Manager oder Tenant Manager

Wenn ein Grid Manager oder der Tenant Manager-Dienst ausfällt, wird das Failover von HA-Gruppen nicht ausgelöst.

Wenn Sie sich bei einem Failover beim Grid Manager oder beim Tenant Manager angemeldet haben, werden Sie abgemeldet und müssen sich erneut anmelden, um Ihre Aufgabe fortzusetzen.

Einige Wartungsvorgänge können nicht ausgeführt werden, wenn der primäre Admin-Node nicht verfügbar ist. Während des Failovers können Sie Ihr StorageGRID-System mit dem Grid-Manager überwachen.



== Einschränkungen bei der Verwendung von HA-Gruppen mit dem CLB-Service

Der Ausfall des CLB-Dienstes löst nicht ein Failover innerhalb der HA-Gruppe aus.


NOTE: Der CLB-Service ist veraltet.
