---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: Um den technischen Support bei der Fehlerbehebung bei Problemen mit Ihrem StorageGRID System zu unterstützen, können Sie manuell eine AutoSupport Meldung auslösen, die gesendet werden soll. 
---
= Senden Sie manuell eine AutoSupport Meldung aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den technischen Support bei der Fehlerbehebung bei Problemen mit Ihrem StorageGRID System zu unterstützen, können Sie manuell eine AutoSupport Meldung auslösen, die gesendet werden soll.

.Was Sie und#8217;ll benötigen
* Sie sind mit einem bei Grid Manager angemeldet xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie haben die Berechtigung Root-Zugriff oder andere Grid-Konfigurationen.


.Schritte
. Wählen Sie *SUPPORT* *Tools* *AutoSupport*.
+
Die Seite AutoSupport wird angezeigt, wobei die Registerkarte *Einstellungen* ausgewählt ist.

. Wählen Sie *vom Benutzer ausgelöste AutoSupport senden* aus.
+
StorageGRID versucht, eine AutoSupport Nachricht an den technischen Support zu senden. Wenn der Versuch erfolgreich ist, werden die *aktuellsten Ergebnisse* und *Letzte erfolgreiche Zeit* Werte auf der Registerkarte *Ergebnisse* aktualisiert. Wenn ein Problem auftritt, werden die *neuesten Ergebnisse*-Werte auf „Fehlgeschlagen“ aktualisiert, und StorageGRID versucht nicht, die AutoSupport-Nachricht erneut zu senden.

+

NOTE: Nachdem Sie eine vom Benutzer ausgelöste AutoSupport-Nachricht gesendet haben, aktualisieren Sie die AutoSupport-Seite im Browser nach 1 Minute, um auf die neuesten Ergebnisse zuzugreifen.


