---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 'Client-Applikationen können sich mithilfe der IP-Adresse eines Grid-Node und der Port-Nummer eines Service auf diesem Node mit StorageGRID verbinden. Bei Konfiguration von Hochverfügbarkeitsgruppen \(HA\) können Client-Applikationen mithilfe der virtuellen IP-Adresse der HA-Gruppe eine Verbindung herstellen.' 
---
= Zusammenfassung: IP-Adressen und Ports für Client-Verbindungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Client-Applikationen können sich mithilfe der IP-Adresse eines Grid-Node und der Port-Nummer eines Service auf diesem Node mit StorageGRID verbinden. Bei Konfiguration von Hochverfügbarkeitsgruppen (High Availability, HA) können Client-Applikationen eine Verbindung über die virtuelle IP-Adresse der HA-Gruppe herstellen.

In dieser Tabelle sind die verschiedenen Verbindungsmethoden aufgeführt, mit denen Clients eine Verbindung zu StorageGRID herstellen können, sowie die für den jeweiligen Verbindungstyp verwendeten IP-Adressen und Ports. Die Anleitung beschreibt das Auffinden dieser Informationen im Grid Manager, wenn die Endpunkte des Load Balancer und Gruppen für Hochverfügbarkeit (HA) bereits konfiguriert sind.

[cols="1a,1a,1a,1a"]
|===
| Wo eine Verbindung hergestellt wird | Dienst, mit dem der Client verbunden ist | IP-Adresse | Port 


 a| 
HA-Gruppe
 a| 
Lastausgleich
 a| 
Virtuelle IP-Adresse einer HA-Gruppe
 a| 
* Endpunkt-Port des Load Balancer




 a| 
HA-Gruppe
 a| 
CLB

*Hinweis:* der CLB-Service ist veraltet.
 a| 
Virtuelle IP-Adresse einer HA-Gruppe
 a| 
S3-Standard-Ports:

* HTTPS: 8082
* HTTP: 8084


Swift-Standardports:

* HTTPS:8083
* HTTP:8085




 a| 
Admin-Node
 a| 
Lastausgleich
 a| 
IP-Adresse des Admin-Knotens
 a| 
* Endpunkt-Port des Load Balancer




 a| 
Gateway-Node
 a| 
Lastausgleich
 a| 
IP-Adresse des Gateway-Node
 a| 
* Endpunkt-Port des Load Balancer




 a| 
Gateway-Node
 a| 
CLB

*Hinweis:* der CLB-Service ist veraltet.
 a| 
IP-Adresse des Gateway-Node

*Hinweis:* standardmäßig sind HTTP-Ports für CLB und LDR nicht aktiviert.
 a| 
S3-Standard-Ports:

* HTTPS: 8082
* HTTP: 8084


Swift-Standardports:

* HTTPS:8083
* HTTP:8085




 a| 
Storage-Node
 a| 
LDR
 a| 
IP-Adresse des Speicherknoten
 a| 
S3-Standard-Ports:

* HTTPS: 18082
* HTTP: 18084


Swift-Standardports:

* HTTPS: 18083
* HTTP:18085


|===
Verwenden Sie eine strukturierte URL, wie unten gezeigt, um einen S3-Client mit dem Load Balancer-Endpunkt einer HA-Gruppe von Gateway-Nodes zu verbinden:

* `https://_VIP-of-HA-group:LB-endpoint-port_`


Wenn beispielsweise die virtuelle IP-Adresse der HA-Gruppe 192.0.2.5 lautet und die Portnummer eines S3 Load Balancer Endpunkts 10443 ist, kann ein S3-Client die folgende URL zur Verbindung mit StorageGRID verwenden:

* `\https://192.0.2.5:10443`


Verwenden Sie eine strukturierte URL, wie unten gezeigt, um einen Swift-Client mit dem Load Balancer-Endpunkt einer HA-Gruppe von Gateway-Nodes zu verbinden:

* `https://_VIP-of-HA-group:LB-endpoint-port_`


Wenn beispielsweise die virtuelle IP-Adresse der HA-Gruppe 192.0.2.6 lautet und die Portnummer eines Swift Load Balancer Endpunkts 10444 ist, kann ein Swift-Client die folgende URL zur Verbindung mit StorageGRID verwenden:

* `\https://192.0.2.6:10444`


Ein DNS-Name kann für die IP-Adresse konfiguriert werden, die Clients zum Herstellen der Verbindung mit StorageGRID verwenden. Wenden Sie sich an Ihren Netzwerkadministrator vor Ort.

.Schritte
. Melden Sie sich mit einem bei Grid Manager an xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
. So suchen Sie die IP-Adresse eines Grid-Knotens:
+
.. Wählen Sie *KNOTEN*.
.. Wählen Sie den Admin-Node, Gateway-Node oder Storage-Node aus, mit dem Sie eine Verbindung herstellen möchten.
.. Wählen Sie die Registerkarte *Übersicht*.
.. Notieren Sie im Abschnitt Node-Informationen die IP-Adressen für den Node.
.. Wählen Sie *Mehr anzeigen*, um IPv6-Adressen und Schnittstellen-Zuordnungen anzuzeigen.
+
Sie können Verbindungen von Client-Anwendungen zu einer beliebigen IP-Adresse in der Liste herstellen:

+
*** *Eth0:* Grid Network
*** *Eth1:* Admin-Netzwerk (optional)
*** *Eth2:* Client-Netzwerk (optional)
+

NOTE: Wenn ein Admin-Node oder ein Gateway-Node angezeigt wird und dieser in einer Hochverfügbarkeitsgruppe der aktive Node ist, wird auf eth2 die virtuelle IP-Adresse der HA-Gruppe angezeigt.





. So finden Sie die virtuelle IP-Adresse einer Hochverfügbarkeitsgruppe:
+
.. Wählen Sie *KONFIGURATION* *Netzwerk* *Hochverfügbarkeitsgruppen*.
.. Notieren Sie in der Tabelle die virtuelle IP-Adresse der HA-Gruppe.


. So finden Sie die Portnummer eines Load Balancer-Endpunkts:
+
.. Wählen Sie *KONFIGURATION* *Netzwerk* *Load Balancer-Endpunkte* aus.
+
Die Seite Load Balancer Endpoints wird angezeigt und zeigt die Liste der bereits konfigurierten Endpunkte an.

.. Wählen Sie einen Endpunkt aus, und wählen Sie *Endpunkt bearbeiten*.
+
Das Fenster Endpunkt bearbeiten wird geöffnet und zeigt weitere Details zum Endpunkt an.

.. Bestätigen Sie, dass der ausgewählte Endpunkt für die Verwendung mit dem korrekten Protokoll konfiguriert ist (S3 oder Swift), und wählen Sie dann *Abbrechen*.
.. Notieren Sie sich die Portnummer für den Endpunkt, den Sie für eine Clientverbindung verwenden möchten.
+

NOTE: Wenn die Portnummer 80 oder 443 ist, wird der Endpunkt nur auf Gateway-Knoten konfiguriert, da diese Ports auf Admin-Nodes reserviert sind. Alle anderen Ports werden sowohl an Gateway-Knoten als auch an Admin-Nodes konfiguriert.




