---
permalink: s3/custom-operations-on-buckets.html 
sidebar: sidebar 
keywords: operations, buckets, custom, custom operations on buckets 
summary: Das StorageGRID System unterstützt benutzerdefinierte Bucket-Vorgänge, die der S3-REST-API hinzugefügt wurden und sich speziell auf das System bezieht. 
---
= Benutzerdefinierte Vorgänge für Buckets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das StorageGRID System unterstützt benutzerdefinierte Bucket-Vorgänge, die der S3-REST-API hinzugefügt wurden und sich speziell auf das System bezieht.

In der folgenden Tabelle sind die von StorageGRID unterstützten benutzerdefinierten Bucket-Vorgänge aufgeführt.

|===
| Betrieb | Beschreibung | Finden Sie weitere Informationen 


 a| 
Get Bucket-Konsistenz
 a| 
Gibt die auf einen bestimmten Bucket angewendete Konsistenzstufe zurück.
 a| 
xref:get-bucket-consistency-request.adoc[Get Bucket-Konsistenzanforderung]



 a| 
PUT Bucket-Konsistenz
 a| 
Legt die Konsistenzstufe für einen bestimmten Bucket fest.
 a| 
xref:put-bucket-consistency-request.adoc[PUT Bucket-Konsistenzanforderung]



 a| 
ZEITPUNKT des letzten Zugriffs FÜR den Bucket ABRUFEN
 a| 
Gibt an, ob Updates der letzten Zugriffszeit für einen bestimmten Bucket aktiviert oder deaktiviert wurden.
 a| 
xref:get-bucket-last-access-time-request.adoc[Anforderung der Uhrzeit des letzten Bucket-Zugriffs ABRUFEN]



 a| 
PUT Bucket-Zeit für den letzten Zugriff
 a| 
Hiermit können Sie Updates der letzten Zugriffszeit für einen bestimmten Bucket aktivieren oder deaktivieren.
 a| 
xref:put-bucket-last-access-time-request.adoc[PUT Anforderung der Uhrzeit des letzten Bucket-Zugriffs]



 a| 
Konfiguration für die Benachrichtigung über Bucket-Metadaten LÖSCHEN
 a| 
Löscht die XML-Konfiguration für die Metadatenbenachrichtigung, die mit einem bestimmten Bucket verknüpft ist.
 a| 
xref:delete-bucket-metadata-notification-configuration-request.adoc[Konfigurationsanforderung für Bucket-Metadaten-Benachrichtigungen LÖSCHEN]



 a| 
Konfiguration der Bucket-Metadaten-Benachrichtigungen ABRUFEN
 a| 
Gibt die XML-XML-Benachrichtigungskonfiguration für Metadaten zurück, die einem bestimmten Bucket zugeordnet ist.
 a| 
xref:get-bucket-metadata-notification-configuration-request.adoc[Konfigurationsanforderung FÜR Bucket-Metadaten-Benachrichtigungen ABRUFEN]



 a| 
PUT Bucket-Metadaten-Benachrichtigungskonfiguration
 a| 
Konfiguriert den Metadaten-Benachrichtigungsdienst für einen Bucket
 a| 
xref:put-bucket-metadata-notification-configuration-request.adoc[PUT Anforderung der Bucket-Metadaten-Benachrichtigung]



 a| 
Bucket mit Compliance-Einstellungen
 a| 
Veraltet und nicht unterstützt: Sie können keine neuen Buckets mit aktivierter Compliance mehr erstellen.
 a| 
xref:deprecated-put-bucket-request-modifications-for-compliance.adoc[Veraltet: Put Bucket mit Compliance-Einstellungen]



 a| 
Bucket-Compliance
 a| 
Veraltet, aber unterstützt: Gibt die Compliance-Einstellungen zurück, die derzeit für einen vorhandenen Legacy-konformen Bucket wirksam sind.
 a| 
xref:deprecated-get-bucket-compliance-request.adoc[Veraltet: GET Bucket-Compliance-Anforderung]



 a| 
BUCKET-Compliance
 a| 
Veraltet, aber unterstützt: Ermöglicht es Ihnen, die Compliance-Einstellungen für einen vorhandenen, älteren konformen Bucket zu ändern.
 a| 
xref:deprecated-put-bucket-compliance-request.adoc[Veraltet: PUT Bucket-Compliance-Anforderung]

|===
xref:s3-operations-tracked-in-audit-logs.adoc[S3-Vorgänge werden in den Audit-Protokollen protokolliert]
