---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html 
sidebar: sidebar 
keywords: ilm manage object rules 
summary: 'Der Grid-Administrator erstellt Informationen Lifecycle Management \(ILM\)-Regeln zum Management von Objektdaten, die aus S3-REST-API-Client-Applikationen in das StorageGRID-System aufgenommen wurden. Diese Regeln werden dann zur ILM-Richtlinie hinzugefügt, um zu bestimmen, wie und wo Objektdaten im Laufe der Zeit gespeichert werden.' 
---
= Managen von Objekten durch StorageGRID ILM-Regeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Grid-Administrator erstellt Informationen Lifecycle Management (ILM)-Regeln für das Management von Objektdaten, die von S3-REST-API-Client-Applikationen in das StorageGRID-System aufgenommen werden. Diese Regeln werden dann zur ILM-Richtlinie hinzugefügt, um zu bestimmen, wie und wo Objektdaten im Laufe der Zeit gespeichert werden.

ILM-Einstellungen bestimmen die folgenden Aspekte eines Objekts:

* *Geographie*
+
Der Speicherort der Objektdaten kann entweder im StorageGRID-System (Storage-Pool) oder in einem Cloud-Storage-Pool gespeichert werden.

* * Speicherklasse*
+
Storage-Typ zur Speicherung von Objektdaten, z. B. Flash oder rotierende Festplatte

* *Verlustschutz*
+
Wie viele Kopien erstellt werden und welche Arten von Kopien erstellt werden: Replizierung, Erasure Coding oder beides.

* *Aufbewahrung*
+
Es ändert sich im Laufe der Zeit, wie Objektdaten verwaltet werden, wo sie gespeichert sind und wie sie vor Verlust geschützt sind.

* *Schutz während der Aufnahme*
+
Methode zum Schutz von Objektdaten bei der Aufnahme: Synchrone Platzierung (mit ausgeglichenen oder strengen Optionen für das Aufnahmeverhalten) oder Erstellung von vorläufigen Kopien (unter Verwendung der Option Dual-Commit)



ILM-Regeln können Objekte filtern und auswählen. Bei mit S3 aufgenommenen Objekten können ILM-Regeln Objekte auf Basis der folgenden Metadaten filtern:

* Mandantenkonto
* Bucket-Name
* Aufnahmezeit
* Taste
* Zeitpunkt Des Letzten Zugriffs
+

NOTE: Standardmäßig werden Updates der letzten Zugriffszeit für alle S3 Buckets deaktiviert. Wenn Ihr StorageGRID System eine ILM-Regel enthält, die die Option „Last Access Time“ verwendet, müssen Sie für die in dieser Regel angegebenen S3-Buckets Updates für die letzte Zugriffszeit aktivieren. Sie können Updates der letzten Zugriffszeit mit dem Kontrollkästchen PUT Bucket Last Access Time (letzte Zugriffszeit), dem Kontrollkästchen *S3* *Buckets* *Letzter Zugriffszeit konfigurieren* im Tenant Manager oder mit der Tenant Management API aktivieren. Beachten Sie bei der Aktivierung von Updates der letzten Zugriffszeit, dass die Performance von StorageGRID möglicherweise reduziert wird, insbesondere bei Systemen mit kleinen Objekten.

* Speicherortbeschränkung
* Objektgröße
* Benutzermetadaten
* Objekt-Tag


Weitere Informationen zum ILM finden Sie in den Anweisungen zum Managen von Objekten mit Information Lifecycle Management.

.Verwandte Informationen
xref:../tenant/index.adoc[Verwenden Sie das Mandantenkonto]

xref:../ilm/index.adoc[Objektmanagement mit ILM]

xref:put-bucket-last-access-time-request.adoc[PUT Anforderung der Uhrzeit des letzten Bucket-Zugriffs]
