---
permalink: s3/use-s3-select.html 
sidebar: sidebar 
keywords: use S3 Select, S3 Select 
summary: StorageGRID unterstützt die folgenden AWS S3 Select-Klauseln, Datentypen, Operatoren und reservierte Schlüsselwörter für DEN Befehl SELECT Object Content. 
---
= Verwenden Sie S3 Select
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID unterstützt die folgenden AWS S3 Select-Klauseln, Datentypen und Operatoren für das xref:select-object-content.adoc[SelectObjectContent, Befehl].


NOTE: Nicht aufgeführte Elemente werden nicht unterstützt.

Syntax finden Sie unter xref:select-object-content.adoc[SelektierObjectContent]. Weitere Informationen zu S3 Select finden Sie im https://["AWS-Dokumentation für S3 Select"^].

Nur Mandantenkonten, für die S3 Select aktiviert ist, können SelectObjectContent-Abfragen ausgeben. Siehe xref:../admin/manage-s3-select-for-tenant-accounts.adoc[Überlegungen und Anforderungen bei der Verwendung von S3 Select].



== Klauseln

* Wählen Sie die Liste aus
* FROM-Klausel
* WHERE-Klausel
* BEGRENZUNGSKLAUSEL




== Datentypen

* bool
* Ganzzahl
* Zeichenfolge
* Schweben
* Dezimal, numerisch
* Zeitstempel




== Operatoren



=== Logische Operatoren

* UND
* NICHT
* ODER




=== Vergleichsoperatoren

* 
* 
* lt;=
* gt;=
* =
* =
* 
* !=
* ZWISCHEN
* IN




=== Operatoren für die Musteranpassung

* GEFÄLLT MIR
* _
* %




=== Einheitliche Operatoren

* IST NULL
* IST NICHT NULL




=== Mathematische Operatoren

* +
* -
* *
* /
* %


StorageGRID folgt dem Präzedenzfall für AWS S3 Select.



== Aggregatfunktionen

* DURCHSCHN.()
* ANZAHL (*)
* MAX.()
* MIN.()
* SUMME()




== Bedingte Funktionen

* FALL
* ZUSAMMENSCHMELZEN
* NULL LIF




== Konvertierungsfunktionen

* CAST (für unterstützten Datentyp)




== Datumsfunktionen

* DATUM_HINZUFÜGEN
* DATE_DIFF
* EXTRAHIEREN
* TO_STRING
* TO_ZEITSTEMPEL
* UTCNOW




== Zeichenfolgenfunktionen

* CHAR_LENGTH, CHARACTER_LENGTH
* NIEDRIGER
* TEILSTRING
* TRIMMEN
* OBEN

