---
permalink: s3/use-s3-object-lock-default-bucket-retention.html 
sidebar: sidebar 
keywords: s3 object lock, default bucket retention 
summary: Wenn in einem Bucket S3-Objektsperre aktiviert ist, können Sie einen Standardaufbewahrungsmodus und einen Standardaufbewahrungszeitraum angeben, der auf jedes dem Bucket hinzugefügte Objekt angewendet wird. 
---
= S3 Object Lock Standard-Bucket-Aufbewahrung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn in einem Bucket S3-Objektsperre aktiviert ist, können Sie einen Standardaufbewahrungsmodus und einen Standardaufbewahrungszeitraum angeben, der auf jedes dem Bucket hinzugefügte Objekt angewendet wird.

* S3 Object Lock kann während der Bucket-Erstellung für einen Bucket aktiviert oder deaktiviert werden.
* Wenn S3 Object Lock für einen Bucket aktiviert ist, können Sie die Standardaufbewahrung für den Bucket konfigurieren.
* Standard-Aufbewahrungskonfiguration gibt an:
+
** Standard-Aufbewahrungsmodus: StorageGRID unterstützt nur den „COMPLIANCE“-Modus.
** Standardaufbewahrungszeitraum in Tagen oder Jahren






== Konfiguration der Objektsperre ABRUFEN

Mit der Konfigurationsanforderung FÜR DIE OBJEKTSPERRE ABRUFEN können Sie festlegen, ob die Objektsperre für einen Bucket aktiviert ist. Wenn diese Option aktiviert ist, überprüfen Sie, ob für den Bucket ein Standardmodus für die Aufbewahrung und ein Aufbewahrungszeitraum konfiguriert ist.

Wenn neue Objektversionen in den Bucket aufgenommen werden, wird der standardmäßige Aufbewahrungsmodus angewendet, wenn `x-amz-object-lock-mode` Ist nicht angegeben. Der Standardaufbewahrungszeitraum wird verwendet, um das Aufbewahrungsdatum von IF zu berechnen `x-amz-object-lock-retain-until-date` Ist nicht angegeben.

Sie müssen über die berechtigung s3:GetBucketObjectLockConfiguration verfügen oder als Account root dienen, um diesen Vorgang abzuschließen.



=== Anforderungsbeispiel

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?object-lock HTTP/1.1
Host: _host_
Accept-Encoding: identity
User-Agent: aws-cli/1.18.106 Python/3.8.2 Linux/4.4.0-18362-Microsoft botocore/1.17.29
x-amz-date: _date_
x-amz-content-sha256: _authorization string_
Authorization: _authorization string_
----


=== Antwortbeispiel

[listing]
----
HTTP/1.1 200 OK
x-amz-id-2: iVmcB7OXXJRkRH1FiVq1151/T24gRfpwpuZrEG11Bb9ImOMAAe98oxSpXlknabA0LTvBYJpSIXk=
x-amz-request-id: B34E94CACB2CEF6D
Date: Fri, 04 Sep 2020 22:47:09 GMT
Transfer-Encoding: chunked
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
<ObjectLockConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <ObjectLockEnabled>Enabled</ObjectLockEnabled>
    <Rule>
        <DefaultRetention>
            <Mode>COMPLIANCE</Mode>
            <Years>6</Years>
        </DefaultRetention>
    </Rule>
</ObjectLockConfiguration>
----


== PUT Objekt Lock-Konfiguration

Die Konfigurationsanforderung FÜR PUT Object Lock ermöglicht es Ihnen, den Standardaufbewahrungsmodus und den Standardaufbewahrungszeitraum für einen Bucket zu ändern, in dem die Objektsperre aktiviert ist. Sie können auch zuvor konfigurierte Standardeinstellungen entfernen.

Wenn neue Objektversionen in den Bucket aufgenommen werden, wird der standardmäßige Aufbewahrungsmodus angewendet, wenn `x-amz-object-lock-mode` Ist nicht angegeben. Der Standardaufbewahrungszeitraum wird verwendet, um das Aufbewahrungsdatum von IF zu berechnen `x-amz-object-lock-retain-until-date` Ist nicht angegeben.

Wenn der Standardaufbewahrungszeitraum nach der Aufnahme einer Objektversion geändert wird, bleibt das „bis-Aufbewahrung“-Datum der Objektversion identisch und wird im neuen Standardaufbewahrungszeitraum nicht neu berechnet.

Sie müssen über die berechtigung s3:PutBucketObjectLockConfiguration verfügen oder als Account root dienen, um diesen Vorgang abzuschließen.

Der `Content-MD5` Der Anforderungskopf muss in der PUT-Anforderung angegeben werden.



=== Anforderungsbeispiel

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?object-lock HTTP/1.1
Accept-Encoding: identity
Content-Length: 308
Host: _host_
Content-MD5: _request header_
User-Agent: s3sign/1.0.0 requests/2.24.0 python/3.8.2
X-Amz-Date: _date_
X-Amz-Content-SHA256: _authorization string_
Authorization: _authorization string_

<ObjectLockConfiguration>
    <ObjectLockEnabled>Enabled</ObjectLockEnabled>
    <Rule>
        <DefaultRetention>
            <Mode>COMPLIANCE</Mode>
            <Years>6</Years>
        </DefaultRetention>
    </Rule>
</ObjectLockConfiguration>
----