---
permalink: monitor/comparing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: how to compare alerts and alarms 
summary: Es gibt eine Reihe von Ähnlichkeiten zwischen dem Alarmsystem und dem alten Alarmsystem, aber das Alarmsystem bietet erhebliche Vorteile und ist einfacher zu bedienen. 
---
= Vergleichen von Warnungen und Alarmen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt eine Reihe von Ähnlichkeiten zwischen dem Alarmsystem und dem alten Alarmsystem, aber das Alarmsystem bietet erhebliche Vorteile und ist einfacher zu bedienen.

In der folgenden Tabelle erfahren Sie, wie Sie ähnliche Vorgänge ausführen.

[cols="1a,1a,1a"]
|===
|  | Meldungen | Alarme (Altsystem) 


 a| 
Wie sehe ich, welche Alarme oder Alarme aktiv sind?
 a| 
* Klicken Sie auf dem Dashboard auf den Link *Aktuelle Alarme*.
* Wählen Sie die Warnmeldung auf der Seite *NODES* *Übersicht* aus.
* Wählen Sie *ALERTS* *Current*.


xref:viewing-current-alerts.adoc[Anzeigen aktueller Warnmeldungen]
 a| 
Wählen Sie *SUPPORT* *Alarme (alt)* *Aktuelle Alarme*.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Was bewirkt, dass eine Warnung oder ein Alarm ausgelöst wird?
 a| 
Alarme werden ausgelöst, wenn ein Prometheus-Ausdruck in einer Alarmregel für die spezifische Triggerbedingung und -Dauer als wahr bewertet wird.

xref:view-alert-rules.adoc[Zeigen Sie Alarmregeln an]
 a| 
Alarme werden ausgelöst, wenn ein StorageGRID-Attribut einen Schwellenwert erreicht.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wie kann ich das zugrunde liegende Problem lösen, wenn eine Meldung oder ein Alarm ausgelöst wird?
 a| 
Die empfohlenen Aktionen für eine Warnmeldung sind in E-Mail-Benachrichtigungen enthalten und stehen auf den Alerts-Seiten im Grid Manager zur Verfügung.

Falls erforderlich, werden weitere Informationen in der StorageGRID-Dokumentation bereitgestellt.

xref:alerts-reference.adoc[Alerts Referenz]
 a| 
Sie können sich über einen Alarm informieren, indem Sie den Attributnamen auswählen oder in der StorageGRID-Dokumentation nach einem Alarmcode suchen.

xref:alarms-reference.adoc[Alarmreferenz (Altsystem)]



 a| 
Wo kann ich eine Liste der Alarme oder Alarme sehen, die gelöst wurden?
 a| 
Wählen Sie *ALERTS* *aufgelöst*.

xref:viewing-resolved-alerts.adoc[Anzeigen von behobenen Warnmeldungen]
 a| 
Wählen Sie *SUPPORT* *Alarme (alt)* *Historische Alarme* aus.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wo kann ich die Einstellungen verwalten?
 a| 
Wählen Sie *ALERTS* *Regeln*.

xref:managing-alerts.adoc[Verwalten von Meldungen]
 a| 
Wählen Sie *SUPPORT*. Verwenden Sie dann die Optionen im Abschnitt *Alarme (alt)* des Menüs.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Welche Benutzergruppenberechtigungen brauche ich?
 a| 
* Jeder, der sich beim Grid Manager anmelden kann, kann aktuelle und behobene Warnmeldungen anzeigen.
* Sie müssen über die Berechtigung zum Verwalten von Warnungen verfügen, um Stille, Warnmeldungen und Alarmregeln zu verwalten.


xref:../admin/index.adoc[StorageGRID verwalten]
 a| 
* Jeder, der sich beim Grid Manager anmelden kann, kann ältere Alarme anzeigen.
* Sie müssen über die Berechtigung Alarme quittieren verfügen, um Alarme zu quittieren.
* Zur Verwaltung globaler Alarme und E-Mail-Benachrichtigungen müssen Sie sowohl über die Seitenkonfiguration der Grid-Topologie als auch über andere Grid-Konfigurationen verfügen.


xref:../admin/index.adoc[StorageGRID verwalten]



 a| 
Wie managt ich E-Mail-Benachrichtigungen?
 a| 
Wählen Sie *ALERTS* *E-Mail-Einrichtung*.

*Hinweis:* Da Alarme und Alarme unabhängige Systeme sind, wird das E-Mail-Setup für Alarm- und AutoSupport-Benachrichtigungen nicht für Benachrichtigungen verwendet. Sie können jedoch denselben E-Mail-Server für alle Benachrichtigungen verwenden.

xref:email-alert-notifications.adoc[Richten Sie E-Mail-Benachrichtigungen für Warnmeldungen ein]
 a| 
Wählen Sie *SUPPORT* *Alarme (alt)* *Legacy E-Mail-Einrichtung*.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wie verwalte ich SNMP Benachrichtigungen?
 a| 
Wählen Sie *KONFIGURATION* *Überwachung* *SNMP-Agent*.

xref:using-snmp-monitoring.adoc[Verwenden Sie SNMP-Überwachung]
 a| 
Wählen Sie *KONFIGURATION* *Überwachung* *SNMP-Agent*.

xref:using-snmp-monitoring.adoc[Verwenden Sie SNMP-Überwachung]

*Hinweis*: SNMP-Benachrichtigungen werden nicht für jeden Alarm oder Alarm Schweregrad gesendet.

xref:alarms-that-generate-snmp-notifications.adoc[Warnmeldungen, die SNMP-Benachrichtigungen generieren (Legacy-System)]



 a| 
Wie kontrolliere ich, wer Benachrichtigungen erhält?
 a| 
. Wählen Sie *ALERTS* *E-Mail-Einrichtung*.
. Geben Sie im Abschnitt *Empfänger* eine E-Mail-Adresse für jede E-Mail-Liste oder Person ein, die eine E-Mail erhalten soll, wenn eine Benachrichtigung erfolgt.


xref:email-alert-notifications.adoc[Richten Sie E-Mail-Benachrichtigungen für Warnmeldungen ein]
 a| 
. Wählen Sie *SUPPORT* *Alarme (alt)* *Legacy E-Mail-Einrichtung*.
. Mailingliste wird erstellt.
. Wählen Sie *Benachrichtigungen*.
. Wählen Sie die Mailingliste aus.


xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Welche Admin Nodes senden Benachrichtigungen?
 a| 
Ein einziger Admin-Node (der „`bevorzugte Absender`“).

xref:../admin/index.adoc[StorageGRID verwalten]
 a| 
Ein einziger Admin-Node (der „`bevorzugte Absender`“).

xref:../admin/index.adoc[StorageGRID verwalten]



 a| 
Wie kann ich einige Benachrichtigungen unterdrücken?
 a| 
. Wählen Sie *ALERTS* *stumm*.
. Wählen Sie die Alarmregel aus, die stummschalten soll.
. Geben Sie eine Dauer für die Stille an.
. Wählen Sie den Schweregrad der Warnmeldung aus, den Sie stummschalten möchten.
. Wählen Sie diese Option aus, um die Stille auf das gesamte Raster, einen einzelnen Standort oder einen einzelnen Knoten anzuwenden.


*Hinweis*: Wenn Sie den SNMP-Agent aktiviert haben, unterdrücken Stille auch SNMP-Traps und informieren.

xref:silencing-alert-notifications.adoc[Benachrichtigung über Stille]
 a| 
. Wählen Sie *SUPPORT* *Alarme (alt)* *Legacy E-Mail-Einrichtung*.
. Wählen Sie *Benachrichtigungen*.
. Wählen Sie eine Mailingliste aus, und wählen Sie *unterdrücken*.


xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wie kann ich alle Benachrichtigungen unterdrücken?
 a| 
Wählen Sie *ALERTS* *stumm* und dann *Alle Regeln*.

*Hinweis*: Wenn Sie den SNMP-Agent aktiviert haben, unterdrücken Stille auch SNMP-Traps und informieren.

xref:silencing-alert-notifications.adoc[Benachrichtigung über Stille]
 a| 
. Wählen Sie *KONFIGURATION* *System* *Anzeigeoptionen*.
. Aktivieren Sie das Kontrollkästchen *Benachrichtigung Alle unterdrücken*.


*Hinweis*: Das Unterdrückung von E-Mail-Benachrichtigungen systemweit unterdrückt auch ereignisgesteuerte AutoSupport-E-Mails.

xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wie kann ich die Bedingungen und Trigger anpassen?
 a| 
. Wählen Sie *ALERTS* *Regeln*.
. Wählen Sie eine Standardregel zum Bearbeiten aus, oder wählen Sie *benutzerdefinierte Regel erstellen*.


xref:editing-alert-rules.adoc[Bearbeiten von Meldungsregeln]

xref:creating-custom-alert-rules.adoc[Erstellen benutzerdefinierter Warnungsregeln]
 a| 
. Wählen Sie *SUPPORT* *Alarme (alt)* *Globale Alarme*.
. Erstellen Sie einen globalen benutzerdefinierten Alarm, um einen Standardalarm zu überschreiben oder ein Attribut zu überwachen, das keinen Standardalarm hat.


xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]



 a| 
Wie deaktiviere ich eine einzelne Warnung oder einen einzelnen Alarm?
 a| 
. Wählen Sie *ALERTS* *Regeln*.
. Wählen Sie die Regel aus, und wählen Sie *Regel bearbeiten*.
. Deaktivieren Sie das Kontrollkästchen *aktiviert*.


xref:disabling-alert-rules.adoc[Deaktivieren von Meldungsregeln]
 a| 
. Wählen Sie *SUPPORT* *Alarme (alt)* *Globale Alarme*.
. Wählen Sie die Regel aus, und wählen Sie das Symbol Bearbeiten aus.
. Deaktivieren Sie das Kontrollkästchen *aktiviert*.


xref:managing-alarms.adoc[Verwalten von Alarmen (Altsystem)]

|===