---
permalink: monitor/disabling-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: Sie können den aktivierten/deaktivierten Status für eine Standard- oder eine benutzerdefinierte Warnungsregel ändern. 
---
= Deaktivieren von Meldungsregeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den aktivierten/deaktivierten Status für eine Standard- oder eine benutzerdefinierte Warnungsregel ändern.

.Was Sie benötigen
* Sie sind mit einem bei Grid Manager angemeldet xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie verfügen über die Berechtigung zum Verwalten von Warnungen oder Stammzugriff.


.Über diese Aufgabe
Wenn eine Meldungsregel deaktiviert ist, werden seine Ausdrücke nicht ausgewertet und es werden keine Warnmeldungen ausgelöst.


IMPORTANT: Im Allgemeinen wird es nicht empfohlen, eine Standardwarnregel zu deaktivieren. Wenn eine Meldungsregel deaktiviert ist, kann ein zugrunde liegendes Problem möglicherweise erst erkannt werden, wenn ein kritischer Vorgang nicht abgeschlossen werden kann.

.Schritte
. Wählen Sie *ALERTS* *Regeln*.
+
Die Seite Alarmregeln wird angezeigt.

. Wählen Sie das Optionsfeld für die Warnungsregel, die deaktiviert oder aktiviert werden soll.
. Wählen Sie *Regel bearbeiten*.
+
Das Dialogfeld Regel bearbeiten wird angezeigt.

. Aktivieren oder deaktivieren Sie das Kontrollkästchen *aktiviert*, um festzustellen, ob diese Alarmregel derzeit aktiviert ist.
+
Wenn eine Alarmregel deaktiviert ist, werden ihre Ausdrücke nicht ausgewertet und es werden keine Warnmeldungen ausgelöst.

+

NOTE: Wenn Sie die Meldungsregel für eine aktuelle Meldung deaktivieren, müssen Sie einige Minuten warten, bis die Meldung nicht mehr als aktive Meldung angezeigt wird.

. Wählen Sie *Speichern*.
+
*Deaktiviert* wird in der Spalte *Status* angezeigt.


