---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: StorageGRID stellt Protokolle bereit, die zum Erfassen von Ereignissen, Diagnosemeldungen und Fehlerbedingungen verwendet werden. Möglicherweise werden Sie gebeten, Protokolldateien zu sammeln und an den technischen Support zu leiten, um bei der Fehlerbehebung zu helfen. 
---
= Referenz für Protokolldateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID stellt Protokolle bereit, die zum Erfassen von Ereignissen, Diagnosemeldungen und Fehlerbedingungen verwendet werden. Möglicherweise werden Sie gebeten, Protokolldateien zu sammeln und an den technischen Support zu leiten, um bei der Fehlerbehebung zu helfen.

Die Protokolle werden wie folgt kategorisiert:

* xref:storagegrid-software-logs.adoc[StorageGRID-Softwareprotokolle]
* xref:deployment-and-maintenance-logs.adoc[Protokoll für Implementierung und Wartung]
* xref:logs-for-third-party-software.adoc[Protokolle für Drittanbietersoftware]
* xref:about-bycast-log.adoc[Etwa bycast.log]



IMPORTANT: Die Details, die für jeden Protokolltyp angegeben sind, dienen nur als Referenz. Die Protokolle sind für erweiterte Fehlerbehebung durch den technischen Support bestimmt. Fortschrittliche Techniken, die die Wiederherstellung des Problemverlaufs mit Hilfe der Audit-Protokolle und der Anwendung Log-Dateien beinhalten, liegen über den Umfang dieser Anweisungen hinaus.

Um auf die Protokolle zuzugreifen, können Sie Logfiles und Systemdaten von einem oder mehreren Knoten als ein einziges Log-File-Archiv (*SUPPORT* *Tools* *Logs*) sammeln. Wenn der primäre Admin-Node nicht verfügbar ist oder einen bestimmten Knoten nicht erreichen kann, können Sie für jeden Grid-Knoten wie folgt auf einzelne Protokolldateien zugreifen:

. Geben Sie den folgenden Befehl ein: `ssh admin@grid_node_IP`
. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


Das Archiv der StorageGRID-Protokolldatei enthält die für jede Kategorie beschriebenen Protokolle sowie zusätzliche Dateien, die Metriken und die Ausgabe des Debug-Befehls enthalten.

[cols="1a,3a"]
|===
| Speicherort der Archivierung | Beschreibung 


| Prüfung  a| 
Während des normalen Systembetriebs erzeugte Überwachungsmeldungen.



| Protokolle von Base-os  a| 
Informationen zu Betriebssystemen, einschließlich StorageGRID-Image-Versionen



| Pakete  a| 
Globale Konfigurationsinformationen (Bundles)



| cassandra  a| 
Cassandra Datenbankinformationen und Reaper Reparaturprotokolle.



| eg  a| 
VCSs-Informationen zu den aktuellen Knoten- und EC-Gruppeninformationen nach Profil-ID.



| Raster  a| 
Allgemeine Grid-Protokolle einschließlich Debug (`bycast.log`) Und `servermanager` Protokolle:



| grid.xml  a| 
Die Grid-Konfigurationsdatei ist über alle Nodes hinweg freigegeben.



| Hagroups  a| 
Hochverfügbarkeitsgruppen – Kennzahlen und Protokolle



| Installieren  a| 
`Gdu-server` Und installieren Protokolle.



| lumberjack.log  a| 
Debug-Meldungen im Zusammenhang mit Protokollerfassung.



| Lambda-Schiedsrichter  a| 
Protokolle in Verbindung mit der S3 Select Proxy-Anforderung.



| Metriken  a| 
Service-Protokolle für Grafana, Jaeger, Node Exporter und Prometheus.



| Falsch  a| 
Miscd-Zugriffs- und Fehlerprotokolle.



| mysql  a| 
Die Konfiguration der MariaDB-Datenbank und die zugehörigen Protokolle.



| Netz  a| 
Protokolle, die von netzwerkbezogenen Skripten und dem dynIP-Dienst erstellt werden.



| Nginx  a| 
Konfigurationsdateien und Protokolle für den Load Balancer. Beinhaltet außerdem Traffic-Protokolle: Grid Manager und Tenant Manager.



| Nginx-gw  a| 
Konfigurationsdateien und Protokolle für den Load Balancer.



| ntp  a| 
NTP-Konfigurationsdatei und -Protokolle



| betriebssystem  a| 
Node- und Grid-Statusdatei, einschließlich Services `pid`.



| Andere  a| 
Log-Dateien unter `/var/local/log` Die nicht in anderen Ordnern erfasst werden.



| perf-  a| 
Performance-Informationen für CPU-, Netzwerk- und Festplatten-I/O.



| prometheus-Data  a| 
Aktuelle Prometheus-Kennzahlen, wenn die Log-Sammlung Prometheus-Daten enthält.



| Bereitstellung  a| 
Protokolle im Zusammenhang mit dem Grid-Bereitstellungsprozess.



| Floß  a| 
Protokolle aus dem in Plattformservices verwendeten Raft-Cluster.



| snmp  a| 
SNMP-Agent-Konfiguration und Alarmzulassungs-/Deny-Listen, die für das Senden von SNMP-Benachrichtigungen verwendet werden.



| Steckdosen-Daten  a| 
Sockendaten für Netzwerk-Debug.



| system-commands.txt  a| 
Ausgabe von StorageGRID-Containerbefehlen. Enthält Systeminformationen wie z. B. Netzwerk- und Festplattenverwendung.

|===
.Verwandte Informationen
xref:collecting-log-files-and-system-data.adoc[Erfassen von Protokolldateien und Systemdaten]
