---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 'Wenn Sie StorageGRID mit dem Simple Network Management Protocol \ (SNMP\) überwachen möchten, müssen Sie den SNMP-Agent konfigurieren, der in StorageGRID enthalten ist.' 
---
= Verwenden Sie SNMP-Überwachung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie StorageGRID mit dem Simple Network Management Protocol (SNMP) überwachen möchten, müssen Sie den SNMP-Agent konfigurieren, der in StorageGRID enthalten ist.

* xref:configuring-snmp-agent.adoc[Konfigurieren Sie den SNMP-Agent]
* xref:updating-snmp-agent.adoc[Aktualisieren Sie den SNMP-Agent]




== Sorgen

Auf jedem StorageGRID-Knoten wird ein SNMP-Agent oder Daemon ausgeführt, der eine Management Information Base (MIB) bereitstellt. Die StorageGRID MIB enthält Tabellen- und Benachrichtigungsdefinitionen für Alarme und Alarme. Die MIB enthält auch Informationen zur Systembeschreibung wie Plattform und Modellnummer für jeden Knoten. Jeder StorageGRID-Knoten unterstützt auch eine Untergruppe von MIB-II-Objekten.

Zunächst ist SNMP auf allen Knoten deaktiviert. Wenn Sie den SNMP-Agent konfigurieren, erhalten alle StorageGRID-Knoten die gleiche Konfiguration.

Der StorageGRID SNMP Agent unterstützt alle drei Versionen des SNMP-Protokolls. Es bietet schreibgeschützten MIB-Zugriff für Abfragen, und es kann zwei Arten von ereignisgesteuerten Benachrichtigungen an ein Verwaltungssystem senden:

* *Traps* sind Benachrichtigungen, die vom SNMP-Agent gesendet werden, die keine Bestätigung durch das Verwaltungssystem erfordern. Traps dienen dazu, das Managementsystem über etwas innerhalb von StorageGRID zu informieren, wie z. B. eine Warnung, die ausgelöst wird.
+
Traps werden in allen drei Versionen von SNMP unterstützt.

* *Informiert* sind ähnlich wie Traps, aber sie erfordern eine Bestätigung durch das Management-System. Wenn der SNMP-Agent innerhalb einer bestimmten Zeit keine Bestätigung erhält, wird die Benachrichtigung erneut gesendet, bis eine Bestätigung empfangen wurde oder der maximale Wiederholungswert erreicht wurde.
+
Die Informationsunterstützung wird in SNMPv2c und SNMPv3 unterstützt.



Trap- und Inform-Benachrichtigungen werden in folgenden Fällen versendet:

* Eine Standardwarnung oder eine benutzerdefinierte Meldung wird für jeden Schweregrad ausgelöst. Um SNMP-Benachrichtigungen für eine Warnung zu unterdrücken, müssen Sie eine Stille für die Warnung konfigurieren. Benachrichtigungen werden von jedem Admin-Node gesendet, der als bevorzugter Absender konfiguriert wurde.
+
Jeder Alarm wird einem von drei Trap-Typen basierend auf dem Schweregrad des Alarms zugeordnet: ActiveMinorAlert, activeMajorAlert und activeCriticalAlert. Beschreibungen der Warnmeldungen, die diese Traps auslösen können, finden Sie im xref:alerts-reference.adoc[Alerts Referenz].

* Bestimmte Alarme (Altsystem) werden mit einem bestimmten Schweregrad oder höher ausgelöst.
+

NOTE: SNMP-Benachrichtigungen werden nicht für jeden Alarm oder jeden Schweregrad gesendet.





== Unterstützung von SNMP-Versionen

Die Tabelle bietet eine allgemeine Zusammenfassung der unterstützten SNMP-Versionen.

|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
Abfragen
 a| 
Schreibgeschützte MIB-Abfragen
 a| 
Schreibgeschützte MIB-Abfragen
 a| 
Schreibgeschützte MIB-Abfragen



 a| 
Abfrageauthentifizierung
 a| 
Community-Zeichenfolge
 a| 
Community-Zeichenfolge
 a| 
Benutzer des benutzerbasierten Sicherheitsmodells (USM)



 a| 
Benachrichtigungen
 a| 
Nur Traps
 a| 
Traps und informiert
 a| 
Traps und informiert



 a| 
Benachrichtigungsauthentifizierung
 a| 
Standard-Trap-Community oder eine benutzerdefinierte Community-Zeichenfolge für jedes Trap-Ziel
 a| 
Standard-Trap-Community oder eine benutzerdefinierte Community-Zeichenfolge für jedes Trap-Ziel
 a| 
USM-Benutzer für jedes Trap-Ziel

|===


== Einschränkungen

* StorageGRID unterstützt schreibgeschützten MIB-Zugriff. Lese-Schreibzugriff wird nicht unterstützt.
* Alle Nodes im Grid erhalten dieselbe Konfiguration.
* SNMPv3: StorageGRID unterstützt den Transport Support Mode (TSM) nicht.
* SNMPv3: Das einzige unterstützte Authentifizierungsprotokoll ist SHA (HMAC-SHA-96).
* SNMPv3: Das einzige unterstützte Datenschutzprotokoll ist AES.




== Auf die MIB zugreifen

Sie können auf die MIB-Definitionsdatei an der folgenden Stelle auf einem beliebigen StorageGRID-Knoten zugreifen:

`/usr/share/snmp/mibs/NETAPP-STORAGEGRID-MIB.txt`

.Verwandte Informationen
* xref:alerts-reference.adoc[Alerts Referenz]
* xref:alarms-reference.adoc[Alarmreferenz (Altsystem)]
* xref:alarms-that-generate-snmp-notifications.adoc[Warnmeldungen, die SNMP-Benachrichtigungen generieren (Legacy-System)]
* xref:silencing-alert-notifications.adoc[Benachrichtigung über Stille]

