---
permalink: maintain/deploying-new-linux-hosts.html 
sidebar: sidebar 
keywords: storagegrid, deploy linux host, new host, new linux host 
summary: Bis auf ein paar Ausnahmen bereiten Sie die neuen Hosts wie während der Erstinstallation vor. 
---
= Implementieren Sie neue Linux-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bis auf ein paar Ausnahmen bereiten Sie die neuen Hosts wie während der Erstinstallation vor.

Um neue oder neu installierte physische oder virtuelle Linux-Hosts bereitzustellen, befolgen Sie das Verfahren zur Vorbereitung der Hosts in der StorageGRID-Installationsanleitung für Ihr Linux-Betriebssystem.

Dieses Verfahren umfasst Schritte zur Durchführung folgender Aufgaben:

. Installieren Sie Linux.
. Konfigurieren Sie das Hostnetzwerk.
. Hostspeicher konfigurieren.
. Die Container-Engine einbauen.
. Installieren Sie den StorageGRID Host Service.
+

IMPORTANT: Beenden Sie den Vorgang „`StorageGRID Host Service` installieren“ in den Installationsanweisungen. Starten Sie nicht die Aufgabe „`DBereitstellung von Grid-Nodes`“.



Beachten Sie bei der Durchführung dieser Schritte die folgenden wichtigen Richtlinien:

* Verwenden Sie die gleichen Hostnamen, die Sie auf dem ursprünglichen Host verwendet haben.
* Wenn Sie Shared Storage zur Unterstützung Ihrer StorageGRID Nodes verwenden oder einige oder alle Festplatten oder SSDs von den ausgefallenen auf die Ersatz-Nodes verschoben haben, müssen Sie die gleichen Storage-Zuordnungen wiederherstellen, die auf dem ursprünglichen Host vorhanden waren. Wenn Sie beispielsweise WWIDs und Aliase in verwendet haben `/etc/multipath.conf` Wie in der Installationsanleitung empfohlen, verwenden Sie die gleichen Alias-/WWID-Paare in `/etc/multipath.conf` Auf dem Ersatzhost.
* Wenn der StorageGRID-Node Storage verwendet, der einem NetApp ONTAP System zugewiesen ist, vergewissern Sie sich, dass auf dem Volume keine FabricPool-Tiering-Richtlinie aktiviert ist. Das Deaktivieren von FabricPool Tiering für Volumes, die in Verbindung mit StorageGRID Nodes verwendet werden, vereinfacht die Fehlerbehebung und Storage-Vorgänge.
+

IMPORTANT: Verwenden Sie FabricPool niemals, um StorageGRID-bezogene Daten in das Tiering zurück zu StorageGRID selbst zu verschieben. Das Tiering von StorageGRID-Daten zurück in die StorageGRID verbessert die Fehlerbehebung und reduziert die Komplexität von betrieblichen Abläufen.



.Verwandte Informationen
xref:../rhel/index.adoc[Installieren Sie Red hat Enterprise Linux oder CentOS]

xref:../ubuntu/index.adoc[Installieren Sie Ubuntu oder Debian]
