---
permalink: maintain/gathering-required-materials-site-decom.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Bevor Sie eine Website ausmustern, sind die folgenden Unterlagen erforderlich. 
---
= Sammeln Sie die erforderlichen Materialien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine Website ausmustern, sind die folgenden Unterlagen erforderlich.

|===


| Element | Hinweise 


 a| 
Wiederherstellungspaket `.zip` Datei
 a| 
Sie müssen das neueste Wiederherstellungspaket herunterladen `.zip` Datei (`sgws-recovery-package-id-revision.zip`). Sie können die Recovery Package-Datei verwenden, um das System wiederherzustellen, wenn ein Fehler auftritt.



 a| 
`Passwords.txt` Datei
 a| 
Diese Datei enthält die Passwörter, die für den Zugriff auf Grid-Knoten in der Befehlszeile erforderlich sind und im Wiederherstellungspaket enthalten sind.



 a| 
Provisioning-Passphrase
 a| 
Die Passphrase wird erstellt und dokumentiert, wenn das StorageGRID-System zum ersten Mal installiert wird. Die Provisionierungs-Passphrase befindet sich nicht im `Passwords.txt` Datei:



 a| 
Beschreibung der Topologie des StorageGRID Systems vor der Stilllegung
 a| 
Falls verfügbar, finden Sie eine Dokumentation, die die aktuelle Topologie des Systems beschreibt.

|===
xref:../admin/web-browser-requirements.adoc[Anforderungen an einen Webbrowser]

xref:downloading-recovery-package.adoc[Laden Sie das Recovery Package herunter]
