---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: Wenn Sie einen Endpunkt für den Load Balancer-Dienst konfigurieren möchten und einen Port verwenden möchten, der bereits als Port mit dem Port einer Port-Remap konfiguriert wurde, müssen Sie zunächst die vorhandene Port-Remap entfernen, oder der Endpunkt ist nicht wirksam. Sie müssen ein Skript auf jedem Admin-Knoten und Gateway-Knoten ausführen, der über widersprüchliche neu zugeordnete Ports verfügt, um alle Port-Remaps des Node zu entfernen. 
---
= Entfernen Sie die Port-Remaps
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Endpunkt für den Load Balancer-Dienst konfigurieren möchten und einen Port verwenden möchten, der bereits als Port mit dem Port einer Port-Remap konfiguriert wurde, müssen Sie zunächst die vorhandene Port-Remap entfernen, oder der Endpunkt ist nicht wirksam. Sie müssen auf jedem Admin-Node und Gateway-Node ein Skript ausführen, das über widersprüchliche neu zugeordnete Ports verfügt, um alle Port-Remaps des Node zu entfernen.

.Über diese Aufgabe

CAUTION: Durch dieses Verfahren werden alle Port-Remaps entfernt. Wenden Sie sich an den technischen Support, wenn Sie einige der Rückpläne aufbewahren müssen.

Informationen über das Konfigurieren von Endpunkten für den Load Balancer finden Sie in den Anweisungen zur Verwaltung von StorageGRID.


IMPORTANT: Wenn die Port-Remap Client-Zugriff bietet, sollte der Client neu konfiguriert werden, um einen anderen Port zu verwenden, der, wenn möglich, als Load Balancer-Endpunkt konfiguriert ist, um einen Serviceverlust zu vermeiden, andernfalls führt das Entfernen der Port-Zuordnung zu einem Verlust des Client-Zugriffs und sollte entsprechend geplant werden.


IMPORTANT: Dieses Verfahren ist bei einem StorageGRID System, das als Container auf Bare-Metal-Hosts bereitgestellt wird, nicht möglich. Siehe Anweisungen für xref:removing-port-remaps-on-bare-metal-hosts.adoc[Entfernen von Port-Remaps auf Bare-Metal-Hosts].

.Schritte
. Melden Sie sich bei dem Node an.
+
.. Geben Sie den folgenden Befehl ein: `ssh -p 8022 admin@node_IP`
+
Port 8022 ist der SSH-Port des Basis-OS, während Port 22 der SSH-Port der Container-Engine ist, auf der StorageGRID ausgeführt wird.

.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



. Führen Sie das folgende Skript aus: `remove-port-remap.sh`
. Booten Sie den Node neu.
+
Befolgen Sie die Anweisungen für xref:rebooting-grid-node.adoc[Neubooten eines Grid-Node].

. Wiederholen Sie diese Schritte auf jedem Admin-Node und Gateway-Node mit gegensätzlichen neu zugeordneten Ports.


.Verwandte Informationen
xref:../admin/index.adoc[StorageGRID verwalten]
