---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: Sie können einen Grid-Node von der Befehlshülle des Node herunterfahren. 
---
= Fahren Sie den Grid-Node herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Grid-Node über die Befehlshaber des Node herunterfahren.

.Was Sie und#8217;ll benötigen
* Sie müssen die haben `Passwords.txt` Datei:


Bevor Sie dieses Verfahren durchführen, sollten Sie folgende Punkte beachten:

* Im Allgemeinen sollten Sie nicht mehr als einen Node gleichzeitig herunterfahren, um Unterbrechungen zu vermeiden.
* Schalten Sie einen Node während eines Wartungsvorgangs nicht herunter, es sei denn, er wird ausdrücklich von der Dokumentation oder vom technischen Support dazu aufgefordert.
* Das Herunterfahren basiert auf dem Installationsort des Node, wie folgt:
+
** Durch das Herunterfahren eines VMware-Knotens wird die virtuelle Maschine heruntergefahren.
** Durch das Herunterfahren eines Linux-Node wird der Container heruntergefahren.
** Durch das Herunterfahren eines StorageGRID-Appliance-Node wird der Computing-Controller heruntergefahren.


* Wenn Sie planen, mehr als einen Storage-Node an einem Standort herunterzufahren, beenden Sie die Aufnahme von Objekten an diesem Standort ca. eine Stunde lang, bevor Sie die Nodes herunterfahren.
+
Wenn eine ILM-Regel die *Dual Commit*-Aufnahmeoption verwendet (oder wenn eine Regel die Option *symmetrisch* verwendet und alle erforderlichen Kopien nicht sofort erstellt werden können), setzt StorageGRID alle neu aufgenommenen Objekte sofort auf zwei Storage-Nodes an demselben Standort und wertet ILM später aus. Wenn mehr als ein Storage-Node an einem Standort heruntergefahren wird, sind Sie möglicherweise während des Herunterfahrens nicht in der Lage, auf neu aufgenommene Objekte zuzugreifen. Schreibvorgänge können auch fehlschlagen, wenn am Standort zu wenige Speicherknoten verfügbar bleiben.



.Schritte
. Melden Sie sich beim Grid-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.

. Beenden Sie alle Dienste: `service servermanager stop`
+
Die Dienste können bis zu 15 Minuten zum Herunterfahren dauern. Außerdem können Sie sich möglicherweise per Remote-Zugriff beim System anmelden, um den Shutdown-Prozess zu überwachen.

. Wenn der Node auf einer virtuellen VMware-Maschine ausgeführt wird oder er ein Appliance-Node ist, geben Sie den Befehl zum Herunterfahren aus: `shutdown -h now`
+
Führen Sie diesen Schritt unabhängig vom Ergebnis des aus `service servermanager stop` Befehl.

+

NOTE: Nachdem Sie das ausstellen `shutdown -h now` Befehl auf einem Appliance-Node müssen Sie die Appliance aus- und wieder einschalten, um den Node neu zu starten.

+
Bei diesem Befehl wird der Controller heruntergefahren, das Gerät ist jedoch weiterhin eingeschaltet. Sie müssen den nächsten Schritt abschließen.

. Wenn Sie einen Appliance-Node herunterfahren:
+
** Für die SG100- oder SG1000-Services-Appliance
+
... Schalten Sie das Gerät aus.
... Warten Sie, bis die blaue Betriebs-LED erlischt.


** Für das SG6000-Gerät
+
... Warten Sie, bis die grüne LED Cache Active auf der Rückseite der Storage Controller ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

... Schalten Sie das Gerät aus und warten Sie, bis die blaue Strom-LED ausgeschaltet ist.


** Für die SG5700 Appliance
+
... Warten Sie, bis die grüne LED Cache Active auf der Rückseite des Storage Controllers ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

... Schalten Sie das Gerät aus und warten Sie, bis alle LED- und siebensegmentreichen Anzeigeaktivitäten angehalten sind.






xref:../admin/index.adoc[StorageGRID verwalten]
