---
permalink: sg5700/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: Das Installationsprogramm von StorageGRID Appliance ist möglicherweise nicht verfügbar, wenn Hardwarefehler oder Verkabelungsfehler verhindern, dass der E5700SG-Controller die Boot-Verarbeitung abschließt. 
---
= Hardware-Setup scheint zu hängen (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Installationsprogramm von StorageGRID Appliance ist möglicherweise nicht verfügbar, wenn Hardwarefehler oder Verkabelungsfehler verhindern, dass der E5700SG-Controller die Boot-Verarbeitung abschließt.

.Schritte
. Sehen Sie sich die Codes auf den sieben Segmenten an.
+
Während die Hardware beim Einschalten initialisiert wird, zeigen die beiden sieben Segmente eine Reihe von Codes an. Wenn die Hardware erfolgreich gebootet wurde, werden in den sieben Segmenten verschiedene Codes für jeden Controller angezeigt.

. Überprüfen Sie die Codes auf der Anzeige der sieben Segmente für den E5700SG-Controller.
+

NOTE: Installation und Bereitstellung nehmen Zeit in Anspruch. In einigen Installationsphasen werden dem Installationsprogramm der StorageGRID-Appliance für mehrere Minuten keine Aktualisierungen gemeldet.

+
Wenn ein Fehler auftritt, blinkt die Sieben-Segment-Anzeige eine Sequenz, z. B. ER.

. Um zu verstehen, was diese Codes bedeuten, lesen Sie die folgenden Ressourcen:
+
|===
| Controller | Referenz 


 a| 
E5700SG Controller
 a| 
** „`status-Indikatoren am E5700SG-Controller`“
** „`HE error: Fehler beim Synchronisieren mit SANtricity OS Software`“




 a| 
E2800 Controller
 a| 
_E5700 and E2800 System Monitoring Guide_

*Hinweis:* die für den E-Series E5700 Controller beschriebenen Codes gelten nicht für den E5700SG Controller in der Appliance.

|===
. Falls das Problem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support.


xref:status-indicators-on-e5700sg-controller.adoc[Statusanzeigen auf dem E5700SG-Controller]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[HE-Fehler: Fehler beim Synchronisieren mit SANtricity OS Software]

http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E-Series Systems Documentation Site"^]
