---
permalink: sg5700/he-error-error-synchronizing-with-santricity-os-software.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshooting, HE, error, synchronize, synchronizing, sunconization, SANtricity OS Software, santricity 
summary: Die sieben-Segment-Anzeige auf dem Compute-Controller zeigt EINEN HE-Fehlercode an, wenn das Installationsprogramm der StorageGRID-Appliance nicht mit SANtricity OS Software synchronisiert werden kann. 
---
= HE-Fehler: Fehler beim Synchronisieren mit SANtricity OS Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die sieben-Segment-Anzeige auf dem Compute-Controller zeigt EINEN HE-Fehlercode an, wenn das Installationsprogramm der StorageGRID-Appliance nicht mit SANtricity OS Software synchronisiert werden kann.

.Über diese Aufgabe
Wenn ein HE-Fehlercode angezeigt wird, führen Sie diese Korrekturmaßnahme durch.

.Schritte
. Überprüfen Sie die beiden Verbindungskabel zwischen den beiden Controllern und vergewissern Sie sich, dass die Kabel und SFP+-Transceiver sicher angeschlossen sind.
. Ersetzen Sie je nach Bedarf ein oder beide Kabel bzw. SFP+-Transceiver, und versuchen Sie es erneut.
. Falls das Problem dadurch nicht behoben werden kann, wenden Sie sich an den technischen Support.

