---
permalink: sg5700/upgrading-santricity-os-on-storage-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Um die optimale Funktion des Storage Controllers sicherzustellen, müssen Sie auf die neueste Wartungsversion des SANtricity-Betriebssystems aktualisieren, das für Ihre StorageGRID Appliance geeignet ist. Ermitteln Sie mit dem NetApp Interoperabilitäts-Matrix-Tool \ (IMT\) die zu verwenden ist. Wenden Sie sich an den technischen Support, wenn Sie Hilfe benötigen.' 
---
= Upgrade von SANtricity OS auf Storage Controller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die optimale Funktion des Storage Controllers sicherzustellen, müssen Sie auf die neueste Wartungsversion des SANtricity-Betriebssystems aktualisieren, das für Ihre StorageGRID Appliance geeignet ist. Ermitteln Sie mithilfe des NetApp Interoperabilitäts-Matrix-Tools (IMT), welche Version Sie verwenden sollten. Wenden Sie sich an den technischen Support, wenn Sie Hilfe benötigen.

* Wenn der Storage-Controller SANtricity OS 08.42.20.00 (11.42) oder eine neuere Version verwendet, führen Sie das Upgrade mit dem Grid Manager durch.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Aktualisieren Sie SANtricity OS auf Storage-Controllern mit Grid Manager]

* Wenn der Storage-Controller eine SANtricity OS-Version verwendet, die älter als 08.42.20.00 ist (11.42), führen Sie das Upgrade im Wartungsmodus durch.
+
xref:upgrading-santricity-os-on-e2800-controller-using-maintenance-mode.adoc[Aktualisieren Sie SANtricity OS auf einem E2800 Controller mithilfe des Wartungsmodus]



https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]

https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["NetApp Downloads mit StorageGRID Appliance"^]

xref:../monitor/index.adoc[Monitoring und Fehlerbehebung]
