---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion 
summary: Gehen Sie folgendermaßen vor, um vorhandenen Standorten Grid-Nodes hinzuzufügen oder einen neuen Standort hinzuzufügen, aber Sie können nicht beide Erweiterungstypen gleichzeitig ausführen. 
---
= Grid-Nodes zu vorhandenem Standort hinzufügen oder neuen Standort hinzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie folgendermaßen vor, um vorhandenen Standorten Grid-Nodes hinzuzufügen oder einen neuen Standort hinzuzufügen, aber Sie können nicht beide Erweiterungstypen gleichzeitig ausführen.

.Was Sie benötigen
* Sie haben die Berechtigung Root-Zugriff oder Wartung.
* Alle bestehenden Nodes im Grid sind über alle Standorte hinweg betriebsbereit.
* Alle vorherigen Erweiterungs-, Upgrade-, Stilllegungs- oder Recovery-Verfahren sind abgeschlossen.
+

NOTE: Sie können eine Erweiterung nicht starten, während noch ein weiteres Verfahren zur Erweiterung, Aktualisierung, Wiederherstellung oder aktiven Deaktivierung ausgeführt wird. Sie können jedoch bei Bedarf eine Deaktivierung unterbrechen, um eine Erweiterung zu starten.



.Schritte
. xref:updating-subnets-for-grid-network.adoc[Subnetze für Grid Network aktualisieren].
. xref:deploying-new-grid-nodes.adoc[Neue Grid-Nodes implementieren].
. xref:performing-expansion.adoc[Erweiterung durchführen].

