---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines, storage volumes, expansion 
summary: 'Sie können die Objekt-Storage-Kapazität Ihres StorageGRID Systems erweitern, indem Sie vorhandenen Storage-Nodes Storage-Volumes hinzufügen oder vorhandenen Standorten neue Storage-Nodes hinzufügen. Sie müssen Storage-Kapazität so hinzufügen, dass sie den Anforderungen Ihrer Information Lifecycle Management \(ILM\)-Richtlinie entspricht.' 
---
= Richtlinien zum Hinzufügen von Objektkapazität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Objekt-Storage-Kapazität Ihres StorageGRID Systems erweitern, indem Sie vorhandenen Storage-Nodes Storage-Volumes hinzufügen oder vorhandenen Standorten neue Storage-Nodes hinzufügen. Storage-Kapazität muss so hinzugefügt werden, dass sie den Anforderungen Ihrer Information Lifecycle Management (ILM)-Richtlinie entspricht.



== Richtlinien für das Hinzufügen von Storage Volumes

Lesen Sie vor dem Hinzufügen von Storage-Volumes zu vorhandenen Storage-Nodes die folgenden Richtlinien und Einschränkungen:

* Sie müssen Ihre aktuellen ILM-Regeln prüfen, um festzustellen, wo und wann Storage-Volumes hinzugefügt werden müssen, um die Storage-Kapazität für replizierte oder Erasure-codierte Objekte zu erhöhen. Siehe Anweisungen für xref:../ilm/index.adoc[Verwalten von Objekten mit Information Lifecycle Management].
* Die Metadatenkapazität des Systems kann nicht durch Hinzufügen von Storage-Volumes erhöht werden, da Objektmetadaten nur auf Volume 0 gespeichert werden.
* Jeder softwarebasierte Storage Node kann maximal 16 Storage Volumes unterstützen. Wenn Sie darüber hinaus Kapazität hinzufügen möchten, müssen Sie neue Storage-Nodes hinzufügen.
* Jeder SG6060- oder SG6060X-Appliance kann ein oder zwei Erweiterungs-Shelfs hinzugefügt werden. Mit jedem Erweiterungs-Shelf werden 16 Storage-Volumes hinzugefügt. Bei beiden installierten Erweiterungs-Shelfs kann das SG6060 und SG6060X insgesamt 48 Storage Volumes unterstützen.
* Sie können keine Speicher-Volumes zu einer anderen Speicher-Appliance hinzufügen.
* Sie können die Größe eines vorhandenen Speichervolumens nicht erhöhen.
* Sie können Storage-Volumes nicht gleichzeitig einem Storage-Node hinzufügen, wenn Sie ein System-Upgrade, Recovery-Vorgang oder eine andere Erweiterung durchführen.


Nachdem Sie sich entschieden haben, Storage Volumes hinzuzufügen und festgestellt haben, welche Storage Nodes Sie erweitern müssen, um Ihre ILM-Richtlinie zu erfüllen, befolgen Sie die Anweisungen für Ihren Storage Node-Typ:

* Um ein oder zwei Erweiterungs-Shelfs zu einer SG6060- oder SG6060X-Storage Appliance hinzuzufügen, gehen Sie zu xref:../sg6000/adding-expansion-shelf-to-deployed-sg6060.adoc[Erweiterungs-Shelf für das implementierte SG6060 oder SG6060X hinzufügen].
* Befolgen Sie die Anweisungen für für, um einen softwarebasierten Node zu erhaltenxref:adding-storage-volumes-to-storage-nodes.adoc[Hinzufügen von Storage-Volumes zu Storage-Nodes].




== Richtlinien zum Hinzufügen von Speicherknoten

Lesen Sie vor dem Hinzufügen von Speicherknoten zu vorhandenen Standorten die folgenden Richtlinien und Einschränkungen durch:

* Sie müssen Ihre aktuellen ILM-Regeln prüfen, um festzustellen, wo und wann Storage-Nodes hinzugefügt werden müssen, um den Storage für replizierte oder Erasure-codierte Objekte zu erhöhen. Siehe Anweisungen für xref:../ilm/index.adoc[Verwalten von Objekten mit Information Lifecycle Management].
* Sie sollten nicht mehr als 10 Speicherknoten in einem einzigen Erweiterungsverfahren hinzufügen.
* Sie können Speicherknoten zu mehr als einem Standort in einem einzigen Erweiterungsverfahren hinzufügen.
* Sie können Storage-Nodes und andere Node-Typen in einem einzigen Erweiterungsverfahren hinzufügen.
* Bevor Sie mit dem Erweiterungsvorgang beginnen, müssen Sie bestätigen, dass alle Datenreparaturvorgänge, die im Rahmen einer Wiederherstellung durchgeführt werden, abgeschlossen sind. Siehe xref:../maintain/checking-data-repair-jobs.adoc[Prüfen Sie die Reparatur von Daten].
* Wenn Sie Storage-Nodes vor oder nach einer Erweiterung entfernen müssen, sollten Sie nicht mehr als 10 Storage-Nodes in einem einzigen Dekommissions-Node-Verfahren außer Betrieb nehmen.




== Richtlinien für ADC-Service auf Storage-Nodes

Beim Konfigurieren der Erweiterung müssen Sie festlegen, ob der Dienst Administrative Domain Controller (ADC) auf jedem neuen Speicherknoten enthalten soll. Der ADC-Dienst verfolgt den Standort und die Verfügbarkeit von Grid-Services.

* Das StorageGRID System erfordert eine xref:../maintain/understanding-adc-service-quorum.adoc[Quorum von ADC-Services] Zu jeder Zeit und an jedem Standort verfügbar zu sein.
* Mindestens drei Storage-Nodes an jedem Standort müssen den ADC-Service enthalten.
* Es wird nicht empfohlen, jedem Speicherknoten den ADC-Dienst hinzuzufügen. Die Einbeziehung von zu vielen ADC-Services kann zu Verlangsamungen führen, da die Kommunikation zwischen den Knoten größer ist.
* Ein einzelnes Grid sollte nicht mehr als 48 Storage-Nodes mit dem ADC-Dienst aufweisen. Dies entspricht 16 Standorten mit drei ADC-Diensten an jedem Standort.
* Wenn Sie im Allgemeinen die Einstellung *ADC-Dienst* für einen neuen Knoten auswählen, sollten Sie *automatisch* wählen. Wählen Sie *Ja* nur aus, wenn der neue Knoten einen anderen Speicherknoten ersetzt, der den ADC-Dienst enthält. Da ein Storage-Node nicht stillgelegt werden kann, wenn zu wenige ADC-Dienste verbleiben, wird sichergestellt, dass ein neuer ADC-Service verfügbar ist, bevor der alte Service entfernt wird.
* Der ADC-Dienst kann nicht einem Node hinzugefügt werden, nachdem er bereitgestellt wurde.

