---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: Wenn ein Storage-Node weniger als 16 Storage-Volumes enthält, können Sie seine Kapazität mithilfe von VMware vSphere erhöhen, um Volumes hinzuzufügen. 
---
= VMware: Hinzufügen von Storage Volumes zum Storage-Node
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Storage-Node weniger als 16 Storage-Volumes enthält, können Sie seine Kapazität mithilfe von VMware vSphere erhöhen, um Volumes hinzuzufügen.

.Was Sie und#8217;ll benötigen
* Sie haben Zugriff auf die Anweisungen zur Installation von StorageGRID für VMware Implementierungen.
+
** xref:../vmware/index.adoc[VMware installieren]


* Sie haben die `Passwords.txt` Datei:
* Sie haben spezifische Zugriffsberechtigungen.



IMPORTANT: Versuchen Sie nicht, Speicher-Volumes zu einem Speicherknoten hinzuzufügen, während ein Software-Upgrade, ein Wiederherstellungsverfahren oder ein anderer Erweiterungsvorgang aktiv ist.

Der Storage-Node ist für kurze Zeit nicht verfügbar, wenn Sie Storage Volumes hinzufügen. Sie sollten dieses Verfahren jeweils auf einem Storage-Knoten durchführen, um die Grid-Services für Clients zu beeinträchtigen.

.Schritte
. Installieren Sie bei Bedarf neue Storage Hardware und erstellen Sie neue VMware Datenspeicher.
. Fügen Sie eine oder mehrere Festplatten zur virtuellen Maschine als Speicher hinzu (Objektspeicher).
+
.. Öffnen Sie den VMware vSphere Client.
.. Bearbeiten Sie die Einstellungen der virtuellen Maschine, um eine oder mehrere zusätzliche Festplatten hinzuzufügen.


+
Die Festplatten werden in der Regel als Virtual Machine Disks (VMDKs) konfiguriert. VMDKs sind häufiger verwendet und einfacher zu managen. RDMs können zudem eine bessere Performance für Workloads mit größeren Objektgrößen bieten (z. B. mehr als 100 MB). Weitere Informationen über das Hinzufügen von Festplatten zu virtuellen Maschinen finden Sie in der Dokumentation zu VMware vSphere.

. Starten Sie die virtuelle Maschine neu, indem Sie im VMware vSphere Client die Option *Gastbetriebssystem neu starten* verwenden oder den folgenden Befehl in einer ssh-Sitzung zur virtuellen Maschine eingeben:``sudo reboot``
+

NOTE: Verwenden Sie zum Neustart der virtuellen Maschine nicht *Power Off* oder *Reset*.

. Konfigurieren Sie den neuen Speicher für die Verwendung durch den Speicherknoten:
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei: Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.


.. Konfiguration der neuen Storage Volumes:
+
`sudo add_rangedbs.rb`

+
Dieses Skript sucht neue Speicher-Volumes und fordert Sie zur Formatierung auf.

.. Geben Sie *y* ein, um die Formatierung zu akzeptieren.
.. Wenn eines der Volumes zuvor formatiert wurde, entscheiden Sie, ob Sie sie neu formatieren möchten.
+
*** Geben Sie * y* ein, um die Formatierung neu zu formatieren.
*** Geben Sie *n* ein, um die Neuformatierung zu überspringen.


.. Geben Sie auf Nachfrage *y* ein, um Storage-Services zu beenden.
+
Die Storage-Services werden angehalten, und das `setup_rangedbs.sh` Skript wird automatisch ausgeführt. Nachdem die Volumes als Rangedbs bereit sind, starten die Dienste erneut.



. Überprüfen Sie, ob die Dienste richtig starten:
+
.. Anzeigen einer Liste des Status aller Dienste auf dem Server:
+
`sudo storagegrid-status`

+
Der Status wird automatisch aktualisiert.

.. Warten Sie, bis alle Dienste ausgeführt oder verifiziert sind.
.. Statusbildschirm verlassen:
+
`Ctrl+C`



. Vergewissern Sie sich, dass der Speicherknoten online ist:
+
.. Melden Sie sich mit einem bei Grid Manager an xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
.. Wählen Sie *SUPPORT* > *Tools* > *Grid-Topologie* aus.
.. Wählen Sie *_site_* *_Storage Node_* *LDR* *Storage* aus.
.. Wählen Sie die Registerkarte *Konfiguration* und dann die Registerkarte *Main*.
.. Wenn die Dropdown-Liste *Speicherstatus - gewünscht* auf schreibgeschützt oder offline gesetzt ist, wählen Sie *Online* aus.
.. Wählen Sie *Änderungen Anwenden*.


. So sehen Sie die neuen Objektspeicher:
+
.. Wählen Sie *NODES* *_site_* *_Storage Node_* *Storage* aus.
.. Sehen Sie sich die Details in der Tabelle *Object Stores* an.




Sie können die erweiterte Kapazität der Speicherknoten zum Speichern von Objektdaten verwenden.
