---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 'Die vor- und Nachteile jeder der drei Optionen zum Schutz von Daten bei Aufnahme zu verstehen \(ausgewogen, streng oder Dual Commit\) kann Ihnen bei der Entscheidung helfen, welche für eine ILM-Regel ausgewählt werden soll.' 
---
= Vor- und Nachteile sowie Einschränkungen der Datensicherungsoptionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die vor- und Nachteile der drei Optionen zum Schutz von Daten bei der Aufnahme (ausgewogen, streng oder Dual-Commit) kennen, können Sie leichter entscheiden, welche für eine ILM-Regel ausgewählt werden soll.



== Vorteile der ausgewogenen und strengen Optionen

Im Vergleich zu Dual-Commit, das während der Aufnahme zwischenzeitliche Kopien erstellt, bieten die zwei Optionen zur synchronen Platzierung folgende Vorteile:

* *Bessere Datensicherheit*: Objektdaten werden sofort gemäß den Anweisungen zur Platzierung der ILM-Regel geschützt, die so konfiguriert werden können, dass sie vor einer Vielzahl von Ausfallszenarien, einschließlich des Ausfalls von mehr als einem Speicherort, geschützt werden. Bei zwei Daten kann nur der Schutz vor dem Verlust einer einzelnen lokalen Kopie geschützt werden.
* *Effizienterer Netzbetrieb*: Jedes Objekt wird nur einmal verarbeitet, wie es aufgenommen wird. Da das StorageGRID System die Interimskopien nicht nachverfolgen oder löschen muss, sinkt der Verarbeitungsbedarf und der Datenbankspeicherplatz wird verringert.
* *(ausgewogen) Empfohlen*: Die ausgewogene Option bietet optimale ILM-Effizienz. Die Verwendung der Option „Balanced“ wird empfohlen, es sei denn, es ist ein striktes Aufnahmeverhalten erforderlich oder das Grid erfüllt alle Kriterien für die Verwendung von Dual-Commit.
* *(striktes) Gewissheit über Objektstandorte*: Die strenge Option garantiert, dass Objekte sofort nach den Platzierungsanweisungen in der ILM-Regel gespeichert werden.




== Nachteile der ausgewogenen und strengen Optionen

Im Vergleich zu Dual Commit haben die ausgewogenen und strengen Optionen einige Nachteile:

* *Längere Client-Ingest*: Client-Ingest-Latenzen können länger sein. Wenn Sie die ausgeglichenen und strengen Optionen verwenden, wird eine „`Aufnahme erfolgreich`“-Meldung erst an den Client zurückgegeben, wenn alle mit Erasure Coding verschlüsselten Fragmente oder replizierte Kopien erstellt und gespeichert werden. Objektdaten werden allerdings sehr wahrscheinlich die endgültige Platzierung viel schneller erreichen.
* *(strenge) höhere Aufnahmeraten*: Bei der strikten Option schlägt die Aufnahme fehl, wenn StorageGRID nicht sofort alle Kopien erstellen kann, die in der ILM-Regel angegeben sind. Falls ein benötigter Speicherplatz vorübergehend offline ist oder Netzwerkprobleme auftreten, die zu Verzögerungen beim Kopieren von Objekten zwischen Standorten führen, ist unter Umständen ein hoher Aufnahmefehler zu beobachten.
* *(strict) S3-Multipart-Upload-Platzierungen sind unter Umständen nicht wie erwartet*: Bei strikter Prüfung erwarten Sie, dass Objekte entweder wie in der ILM-Regel beschrieben platziert werden oder dass die Aufnahme fehlschlägt. Bei einem S3-Multipart-Upload wird ILM jedoch für jeden Teil des Objekts während der Aufnahme und für das Objekt als Ganzes bewertet, wenn der mehrteilige Upload abgeschlossen ist. Unter den folgenden Umständen kann dies zu Platzierungen führen, die sich von Ihnen unterscheiden:
+
** *Wenn sich ILM ändert, während ein S3-Multipart-Upload im Gange ist*: Da jedes Teil gemäß der Regel platziert wird, die bei der Aufnahme des Teils aktiv ist, entsprechen einige Teile des Objekts möglicherweise nicht den aktuellen ILM-Anforderungen, wenn der mehrteilige Upload abgeschlossen ist. In diesen Fällen schlägt die Aufnahme des Objekts nicht fehl. Stattdessen werden alle Teile, die nicht korrekt platziert werden, zur ILM-Neubewertung in eine Warteschlange eingereiht und zu einem späteren Zeitpunkt an den richtigen Ort verschoben.
** *Wenn ILM-Regeln Filter auf Größe*: Bei der Bewertung von ILM für ein Teil filtert StorageGRID die Größe des Teils, nicht die Größe des Objekts. Das bedeutet, dass Teile eines Objekts an Standorten gespeichert werden können, die die ILM-Anforderungen für das Objekt als Ganzes nicht erfüllen. Wenn z. B. eine Regel angibt, dass alle Objekte ab 10 GB auf DC1 gespeichert werden, während alle kleineren Objekte an DC2 gespeichert sind, wird bei Aufnahme jeder 1 GB-Teil eines 10-teiligen mehrteiligen Uploads auf DC2 gespeichert. Wenn ILM für das Objekt bewertet wird, werden alle Teile des Objekts auf DC1 verschoben.


* *(strict) Aufnahme scheitert nicht, wenn Objekt-Tags oder Metadaten aktualisiert werden und neu erforderliche Platzierungen nicht gemacht werden können*: Mit strikter, erwarten Sie, dass Objekte entweder wie in der ILM-Regel beschrieben platziert werden oder dass die Aufnahme fehlschlägt. Wenn Sie jedoch Metadaten oder Tags für ein Objekt aktualisieren, das bereits im Raster gespeichert ist, wird das Objekt nicht erneut aufgenommen. Das bedeutet, dass Änderungen an der Objektplatzierung, die durch die Aktualisierung ausgelöst werden, nicht sofort vorgenommen werden. Änderungen an der Platzierung werden vorgenommen, wenn ILM durch normale ILM-Prozesse im Hintergrund neu bewertet wird. Falls erforderliche Platzierungsänderungen nicht vorgenommen werden können (z. B. weil ein neu erforderlicher Standort nicht verfügbar ist), behält das aktualisierte Objekt seine aktuelle Platzierung vor, bis die Platzierungsänderungen möglich sind.




== Einschränkungen bei der Platzierung von Objekten mit den ausgewogenen oder strengen Optionen

Die ausgewogenen oder strengen Optionen können nicht für ILM-Regeln verwendet werden, die eine der folgenden Anweisungen zur Platzierung haben:

* Platzierung in einem Cloud-Storage-Pool am Tag 0
* Platzierung in einem Archiv-Knoten an Tag 0.
* Platzierungen in einem Cloud-Speicherpool oder einem Archivknoten, wenn die Regel eine benutzerdefinierte Erstellungszeit als Referenzzeit hat.


Diese Einschränkungen sind vorhanden, da StorageGRID keine synchronen Kopien in einen Cloud-Speicherpool oder einen Archiv-Node erstellen kann und eine benutzerdefinierte Erstellungszeit auf die vorhandene auflösen kann.



== Auswirkungen von ILM-Regeln und Konsistenzkontrollen auf die Datensicherung

Sowohl Ihre ILM-Regel als auch Ihre Wahl der Konsistenzkontrolle beeinflussen den Schutz von Objekten. Diese Einstellungen können interagieren.

Das für eine ILM-Regel ausgewählte Aufnahmeverhalten wirkt sich beispielsweise auf die anfängliche Platzierung von Objektkopien aus, während sich die beim Speichern eines Objekts verwendete Konsistenzkontrolle auf die anfängliche Platzierung von Objekt-Metadaten auswirkt. Da StorageGRID Zugriff auf die Metadaten eines Objekts und seine Daten benötigt, um Kundenanforderungen zu erfüllen, kann die Auswahl der passenden Sicherungsstufen für Konsistenz und Aufnahme-Verhalten eine bessere Erstsicherung und zuverlässigere Systemantworten ermöglichen.

Hier finden Sie eine kurze Zusammenfassung der in StorageGRID verfügbaren Konsistenzkontrollen:

* *Alle*: Alle Knoten erhalten sofort Objektmetadaten oder die Anfrage schlägt fehl.
* *Stark-global*: Objektmetadaten werden sofort auf alle Seiten verteilt. Garantierte Konsistenz bei Lese-nach-Schreibvorgängen für alle Client-Anfragen an allen Standorten.
* *Strong-site*: Objektmetadaten werden sofort auf andere Knoten am Standort verteilt. Garantiert Konsistenz bei Lese-nach-Schreibvorgängen für alle Client-Anfragen innerhalb eines Standorts.
* *Read-after-New-write*: Sorgt für die Konsistenz von Read-after-write für neue Objekte und eventuelle Konsistenz von Objekt-Updates. Hochverfügbarkeit und garantierte Datensicherung
* *Verfügbar* (eventuelle Konsistenz für KOPFOPERATIONEN): Verhält sich wie das "`read-after-New-write`" Konsistenzniveau, bietet aber nur eventuelle Konsistenz für DEN KOPFBETRIEB.



NOTE: Lesen Sie vor Auswahl einer Konsistenzstufe die vollständige Beschreibung der Consistency Controls in den Anweisungen für xref:../s3/consistency-controls.adoc[S3] Oder xref:../swift/storagegrid-swift-rest-api-operations.adoc[Swift] Client-Applikationen: Vor dem Ändern des Standardwerts sollten Sie die Vorteile und Einschränkungen kennen.



== Beispiel für die Interaktion zwischen Konsistenzkontrolle und ILM-Regel

Angenommen, Sie haben ein Grid mit zwei Standorten mit der folgenden ILM-Regel und der folgenden Einstellung für die Konsistenzstufe:

* *ILM-Regel*: Erstellen Sie zwei Objektkopien, eine am lokalen Standort und eine an einem entfernten Standort. Das strikte Aufnahmeverhalten wird ausgewählt.
* *Konsistenzstufe*: "`strong-global`" (Objektmetadaten werden sofort auf alle Standorte verteilt.)


Wenn ein Client ein Objekt im Grid speichert, erstellt StorageGRID sowohl Objektkopien als auch verteilt Metadaten an beiden Standorten, bevor der Kunde zum Erfolg zurückkehrt.

Das Objekt ist zum Zeitpunkt der Aufnahme der Nachricht vollständig gegen Verlust geschützt. Wenn beispielsweise der lokale Standort kurz nach der Aufnahme verloren geht, befinden sich Kopien der Objektdaten und der Objektmetadaten am Remote-Standort weiterhin. Das Objekt kann vollständig abgerufen werden.

Falls Sie stattdessen dieselbe ILM-Regel und die Konsistenzstufe „`strong-Site`“ verwendet haben, erhält der Client möglicherweise eine Erfolgsmeldung, nachdem die Objektdaten an den Remote Standort repliziert wurden, aber bevor die Objektmetadaten dort verteilt werden. In diesem Fall entspricht die Sicherung von Objektmetadaten nicht dem Schutzniveau für Objektdaten. Falls der lokale Standort kurz nach der Aufnahme verloren geht, gehen Objektmetadaten verloren. Das Objekt kann nicht abgerufen werden.

Die Wechselbeziehung zwischen Konsistenzstufen und ILM-Regeln kann komplex sein. Wenden Sie sich an NetApp, wenn Sie Hilfe benötigen.

.Verwandte Informationen
* xref:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.adoc[Beispiel 5: ILM-Regeln und Richtlinie für striktes Ingest-Verhalten]

