---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: Sie können einen Speicherpool bearbeiten, um seinen Namen zu ändern oder Standorte und Speicherklassen zu aktualisieren. 
---
= Speicherpool bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Speicherpool bearbeiten, um seinen Namen zu ändern oder Standorte und Speicherklassen zu aktualisieren.

.Was Sie benötigen
* Sie sind mit einem bei Grid Manager angemeldet xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie haben spezifische Zugriffsberechtigungen.
* Sie haben die Richtlinien zum Erstellen von Speicherpools überprüft.
* Wenn Sie einen Speicherpool bearbeiten möchten, der von einer Regel in der aktiven ILM-Richtlinie verwendet wird, haben Sie überlegt, wie sich Ihre Änderungen auf die Platzierung von Objektdaten auswirken.


.Über diese Aufgabe
Wenn Sie einem Speicherpool, der in der aktiven ILM-Richtlinie verwendet wird, eine neue Speicherklasse hinzufügen, beachten Sie, dass die Speicherknoten in der neuen Speicherklasse nicht automatisch verwendet werden. Damit StorageGRID die Verwendung einer neuen Storage-Klasse erzwingen kann, müssen Sie eine neue ILM-Richtlinie aktivieren, nachdem Sie den bearbeiteten Speicherpool gespeichert haben.

.Schritte
. Wählen Sie *ILM* *Storage Pools* aus.
+
Die Seite Speicherpools wird angezeigt.

. Wählen Sie das Optionsfeld für den Speicherpool aus, den Sie bearbeiten möchten.
+
Der Speicherpool Alle Speicherknoten kann nicht bearbeitet werden.

. Wählen Sie *Bearbeiten*.
. Ändern Sie bei Bedarf den Namen des Speicherpools.
. Wählen Sie bei Bedarf andere Standorte und Lagersorten aus.
+

NOTE: Sie können die Standort- oder Speicherklasse nicht ändern, wenn der Speicherpool in einem Erasure-Coding-Profil verwendet wird und die Änderung das Erasure-Coding-Schema ungültig machen würde. Wenn beispielsweise ein in einem Erasure Coding-Profil verwendeter Speicherpool derzeit einen Storage-Grade mit nur einem Standort umfasst, können Sie keinen Storage-Grade mit zwei Standorten verwenden, da die Änderung das Erasure Coding-Schema ungültig machen würde.

. Wählen Sie *Speichern*.


.Nachdem Sie fertig sind
Wenn Sie einem Storage-Pool, der in der aktiven ILM-Richtlinie verwendet wird, eine neue Storage-Klasse hinzugefügt haben, aktivieren Sie eine neue ILM-Richtlinie, um die Verwendung der neuen Storage-Klasse durch StorageGRID zu erzwingen. Klonen Sie beispielsweise Ihre vorhandene ILM-Richtlinie und aktivieren Sie dann den Klon.
