---
permalink: ilm/removing-storage-pool.html 
sidebar: sidebar 
keywords: remove storage pool 
summary: Sie können einen Speicherpool entfernen, der nicht verwendet wird. 
---
= Entfernen Sie einen Speicherpool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Speicherpool entfernen, der nicht verwendet wird.

.Was Sie benötigen
* Sie sind mit einem bei Grid Manager angemeldet xref:../admin/web-browser-requirements.adoc[Unterstützter Webbrowser].
* Sie haben spezifische Zugriffsberechtigungen.


.Schritte
. Wählen Sie *ILM* *Storage Pools* aus.
+
Die Seite Speicherpools wird angezeigt.

. Sehen Sie sich die Spalte ILM-Nutzung in der Tabelle an, um zu bestimmen, ob Sie den Speicherpool entfernen können.
+
Ein Speicherpool kann nicht entfernt werden, wenn er in einer ILM-Regel oder in einem Erasure Coding-Profil verwendet wird. Wählen Sie nach Bedarf *Details anzeigen* *ILM-Nutzung* aus, um festzustellen, wo ein Speicherpool verwendet wird.

. Wenn der Speicherpool, den Sie entfernen möchten, nicht verwendet wird, aktivieren Sie das Optionsfeld.
. Wählen Sie *Entfernen*.
. Wählen Sie *OK*.

