---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: Sie können den Zeitpunkt des letzten Zugriffs als Referenzzeit in einer ILM-Regel verwenden. Sie möchten beispielsweise Objekte, die in den letzten drei Monaten auf lokalen Speicherknoten angezeigt wurden, während Sie Objekte verschieben, die noch nicht in letzter Zeit an einen externen Standort betrachtet wurden. Sie können den Zeitpunkt des letzten Zugriffs auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur für Objekte gelten soll, auf die zuletzt an einem bestimmten Datum zugegriffen wurde. 
---
= Verwenden Sie die Zeit für den letzten Zugriff in ILM-Regeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Zeitpunkt des letzten Zugriffs als Referenzzeit in einer ILM-Regel verwenden. Sie möchten beispielsweise Objekte, die in den letzten drei Monaten auf lokalen Speicherknoten angezeigt wurden, während Sie Objekte verschieben, die noch nicht in letzter Zeit an einen externen Standort betrachtet wurden. Sie können den Zeitpunkt des letzten Zugriffs auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur für Objekte gelten soll, auf die zuletzt an einem bestimmten Datum zugegriffen wurde.

.Über diese Aufgabe
Bevor Sie den Zeitpunkt des letzten Zugriffs in einer ILM-Regel verwenden, prüfen Sie die folgenden Aspekte:

* Wenn Sie den Zeitpunkt des letzten Zugriffs als Referenzzeit verwenden, beachten Sie, dass durch das Ändern der Uhrzeit für den letzten Zugriff für ein Objekt keine sofortige ILM-Evaluierung ausgelöst wird. Stattdessen werden die Platzierungen des Objekts bewertet und das Objekt nach Bedarf verschoben, wenn im Hintergrund ILM das Objekt bewertet wird. Dies kann zwei Wochen oder länger dauern, nachdem auf das Objekt zugegriffen wurde.
+
Berücksichtigen Sie diese Latenz bei der Erstellung von ILM-Regeln, die auf Last Access Time basieren, und vermeiden Sie Platzierungen, die kurze Zeiträume (weniger als einen Monat) nutzen.

* Wenn Sie den Zeitpunkt des letzten Zugriffs als erweiterten Filter oder als Referenzzeit verwenden, müssen Sie die Updates der letzten Zugriffszeit für S3-Buckets aktivieren. Sie können den Tenant Manager oder die Mandantenmanagement-API verwenden.
+

NOTE: Updates der letzten Zugriffszeit sind immer für Swift Container aktiviert. Für S3 Buckets sind sie jedoch standardmäßig deaktiviert.

+

IMPORTANT: Beachten Sie, dass eine Aktualisierung der letzten Zugriffszeit die Performance beeinträchtigen kann, insbesondere bei Systemen mit kleinen Objekten. Die Auswirkungen auf die Performance werden dadurch erzielt, dass StorageGRID die Objekte bei jedem Abruf mit neuen Zeitstempel aktualisieren muss.



Die folgende Tabelle fasst zusammen, ob die letzte Zugriffszeit für alle Objekte im Bucket für unterschiedliche Anträgen aktualisiert wird.

[cols="1a,1a,1a"]
|===
| Art der Anfrage | Gibt an, ob die letzte Zugriffszeit aktualisiert wird, wenn Updates der letzten Zugriffszeit deaktiviert sind | Ob die letzte Zugriffszeit aktualisiert wird, wenn Updates der letzten Zugriffszeit aktiviert sind 


 a| 
Anforderung zum Abrufen eines Objekts, seiner Zugriffssteuerungsliste oder seiner Metadaten
 a| 
Nein
 a| 
Ja.



 a| 
Anforderung zum Aktualisieren der Metadaten eines Objekts
 a| 
Ja.
 a| 
Ja.



 a| 
Anforderung zum Kopieren eines Objekts von einem Bucket in einen anderen
 a| 
* Nein, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Ja, für die Quellkopie
* Ja, für die Zielkopie




 a| 
Anforderung zum Abschließen eines mehrteiligen Uploads
 a| 
Ja, für das zusammengesetzte Objekt
 a| 
Ja, für das zusammengesetzte Objekt

|===
.Verwandte Informationen
* xref:../s3/index.adoc[S3 verwenden]
* xref:../tenant/index.adoc[Verwenden Sie ein Mandantenkonto]

