---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Ein Speicherpool ist eine logische Gruppierung von Storage-Nodes oder Archiv-Nodes. Sie konfigurieren Speicherpools, um zu bestimmen, wo das StorageGRID-System Objektdaten und den verwendeten Storage-Typ speichert. 
---
= Was ist ein Speicherpool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Speicherpool ist eine logische Gruppierung von Storage-Nodes oder Archiv-Nodes. Sie konfigurieren Speicherpools, um zu bestimmen, wo das StorageGRID-System Objektdaten und den verwendeten Storage-Typ speichert.

Storage-Pools haben zwei Attribute:

* *Speicherklasse*: Für Storage-Nodes, die relative Performance beim Sichern von Speicher.
* *Standort*: Das Rechenzentrum, in dem Objekte gespeichert werden.


Storage-Pools werden in ILM-Regeln verwendet, um zu bestimmen, wo Objektdaten gespeichert werden. Wenn Sie ILM-Regeln für die Replikation konfigurieren, wählen Sie einen oder mehrere Storage-Pools aus, die entweder Storage-Nodes oder Archiv-Nodes enthalten. Wenn Sie Erasure Coding-Profile erstellen, wählen Sie einen Speicherpool aus, der Storage-Nodes enthält.
