---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: 'Bevor Sie StorageGRID als FabricPool Cloud-Tier anhängen, sollten Sie mit StorageGRID Grid Manager eine Hochverfügbarkeitsgruppe \(HA\) konfigurieren.' 
---
= Best Practices für Hochverfügbarkeitsgruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie StorageGRID als FabricPool Cloud-Tier anhängen, sollten Sie StorageGRID Grid Manager zur Konfiguration einer HA-Gruppe (High Availability, Hochverfügbarkeit) verwenden.



== Was ist eine HA-Gruppe (High Availability, Hochverfügbarkeit)?

Um sicherzustellen, dass der Load Balancer-Service zum Verwalten von FabricPool-Daten immer verfügbar ist, können Sie die Netzwerkschnittstellen mehrerer Admin- und Gateway-Nodes zu einer einzigen Einheit gruppieren, die als HA-Gruppe (High Availability, Hochverfügbarkeit) bezeichnet wird. Wenn der aktive Node in der HA-Gruppe ausfällt, kann der Workload weiterhin von einem anderen Node in der Gruppe gemanagt werden.

Jede HA-Gruppe ermöglicht einen hochverfügbaren Zugriff auf die Shared Services auf den zugehörigen Nodes. Beispielsweise bietet eine HA-Gruppe, die aus Schnittstellen nur auf Gateway-Nodes oder sowohl Admin-Nodes als auch Gateway-Nodes besteht, einen hochverfügbaren Zugriff auf den Shared Load Balancer Service.

Zum Erstellen einer HA-Gruppe führen Sie die folgenden allgemeinen Schritte aus:

. Wählen Sie Netzwerkschnittstellen für einen oder mehrere Admin-Nodes oder Gateway-Nodes aus. Sie können die Grid Network Interface (eth0), die Client Network Interface (eth2) oder eine VLAN-Schnittstelle auswählen.
+

IMPORTANT: Wenn Sie eine VLAN-Schnittstelle zur Trennung des FabricPool-Datenverkehrs verwenden möchten, muss ein Netzwerkadministrator zunächst eine Trunk-Schnittstelle und das entsprechende VLAN konfigurieren. Jedes VLAN wird durch eine numerische ID oder ein Tag identifiziert. Beispielsweise könnte Ihr Netzwerk VLAN 100 für FabricPool-Datenverkehr verwenden.

. Weisen Sie der Gruppe eine oder mehrere virtuelle IP-Adressen (VIP) zu. Clients, z. B. FabricPool, können eine dieser VIP-Adressen verwenden, um eine Verbindung zu StorageGRID herzustellen.
. Geben Sie eine Schnittstelle für die primäre Schnittstelle an, und bestimmen Sie die Prioritätsreihenfolge für alle Backup-Schnittstellen. Die primäre Schnittstelle ist die aktive Schnittstelle, sofern kein Fehler auftritt.


Wenn die HA-Gruppe mehrere Schnittstellen umfasst und die primäre Schnittstelle ausfällt, werden die VIP-Adressen auf die erste Backup-Schnittstelle in der Prioritätsreihenfolge verschoben. Wenn diese Schnittstelle ausfällt, wechseln die VIP-Adressen zur nächsten Backup-Schnittstelle usw. Dieser Failover-Prozess dauert in der Regel nur wenige Sekunden und ist schnell genug, dass Client-Applikationen nur geringe Auswirkungen haben und sich auf normale Wiederholungsmuster verlassen können, um den Betrieb fortzusetzen.

Wenn der Fehler behoben ist und eine Schnittstelle mit höherer Priorität wieder verfügbar wird, werden die VIP-Adressen automatisch auf die Schnittstelle mit der höchsten Priorität verschoben, die verfügbar ist.



== Best Practices für Hochverfügbarkeitsgruppen (High Availability groups, HA-Gruppen

Die Best Practices zum Erstellen einer StorageGRID HA-Gruppe für FabricPool hängen vom Workload ab:

* Wenn Sie FabricPool für Daten mit primären Workloads verwenden möchten, müssen Sie eine HA-Gruppe erstellen, die mindestens zwei Load-Balancing-Nodes umfasst, um eine Unterbrechung beim Datenabruf zu vermeiden.
* Wenn Sie eine FabricPool Richtlinie für das reine Volume-Tiering nur für Snapshots oder nicht für lokale Performance-Tiers (z. B. Disaster Recovery-Standorte oder NetApp SnapMirror Ziele) verwenden möchten, können Sie eine HA-Gruppe mit nur einem Node konfigurieren.


Diese Anweisungen beschreiben die Einrichtung einer HA-Gruppe für Active-Backup HA (ein Node ist aktiv und ein Node ist ein Backup). Möglicherweise verwenden Sie jedoch lieber DNS Round Robin oder Active-Active HA. Informationen zu den Vorteilen dieser anderen HA-Konfigurationen finden Sie unter xref:../admin/configuration-options-for-ha-groups.adoc[Konfigurationsoptionen für HA-Gruppen].
